In [1]:
import numpy as np
import pandas as pd
import pyodbc as pyo
import sqlalchemy as sa
import math
connection_uri = (
    "mssql+pyodbc://TEDPHO0134\TANDT_DP/DP_Tan?driver=ODBC+Driver+17+for+SQL+Server"
)
conn = sa.create_engine(connection_uri)

<h4> Lấy bảng Commision <h4>

In [7]:
cutoff = '202401'
commission_query = f"select * from AGENT_COM_CUTOFF where CUTOFF like '{cutoff}%'"
agent_com = pd.read_sql(commission_query, conn)

In [6]:
py2_query = f"select * from AGENT_COM_CUTOFF where CUTOFF like '{cutoff}%'"

Empty DataFrame
Columns: [Policy No, Product Code, Premium transaction, Premium transaction name, Premium Collected, Collected Date, Applied Premium Date, FYC, RYC, Shared Commission Rate, Policy Status, Policy Year, Frequency of Payment, Issued Date, Effected Date, Terminated Date, Lapse Date, Due Date, Next Due Date, Area Code, Issuing Agent, Servicing Agent, Commission Agent, Transfer Date, Proposal Receive Date, Freelook, RISK_COMMENCE_DATE, Receive Policy date, Premium Year, CUTOFF, RETURN_DATE]
Index: []

[0 rows x 31 columns]

In [8]:
agent_com

,Policy No,Product Code,Premium transaction,Premium transaction name,Premium Collected,Collected Date,Applied Premium Date,FYC,RYC,Shared Commission Rate,...,Servicing Agent,Commission Agent,Transfer Date,Proposal Receive Date,Freelook,RISK_COMMENCE_DATE,Receive Policy date,Premium Year,CUTOFF,RETURN_DATE
0,80000013,ETR1,T642,Contract Issue,191000.0,2014-03-31,2014-03-31,40000.0,0.0,100.0,...,60000005,60000005,2014-03-31,2014-03-29,3570.0,2014-03-28,2014-04-08,1,20240115,None
1,80000013,EE01,T642,Contract Issue,3640000.0,2014-03-31,2014-03-31,764000.0,0.0,100.0,...,60000005,60000005,2014-03-31,2014-03-29,3570.0,2014-03-28,2014-04-08,1,20240115,None
2,80000013,EWR1,T642,Contract Issue,40000.0,2014-03-31,2014-03-31,8000.0,0.0,100.0,...,60000005,60000005,2014-03-31,2014-03-29,3570.0,2014-03-28,2014-04-08,1,20240115,None
3,80000013,EWR1,B522,Premium Collection,40000.0,2014-07-29,2014-07-29,9000.0,0.0,100.0,...,60000005,60000005,2014-03-31,2014-03-29,3570.0,2014-03-28,2014-04-08,1,20240115,None
4,80000013,ETR1,B522,Premium Collection,191000.0,2014-07-29,2014-07-29,40000.0,0.0,100.0,...,60000005,60000005,2014-03-31,2014-03-29,3570.0,2014-03-28,2014-04-08,1,20240115,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3172092,80147010,URC5,T642,Contract Issue,3300000.0,2023-05-31,2023-05-31,1155000.0,0.0,100.0,...,60078191,60078191,2023-05-31,2023-05-31,18.0,2023-05-31,2023-06-08,1,20240126,None
3172093,80147010,URA5,T642,Contract Issue,2148000.0,2023-05-31,2023-05-31,752000.0,0.0,100.0,...,60078191,60078191,2023-05-31,2023-05-31,18.0,2023-05-31,2023-06-08,1,20240126,None
3172094,80147010,RHB1,T642,Contract Issue,500000.0,2023-05-31,2023-05-31,75000.0,0.0,100.0,...,60078191,60078191,2023-05-31,2023-05-31,18.0,2023-05-31,2023-06-08,1,20240126,None
3172095,80147010,RHS1,T642,Contract Issue,4785000.0,2023-05-31,2023-05-31,957000.0,0.0,100.0,...,60078191,60078191,2023-05-31,2023-05-31,18.0,2023-05-31,2023-06-08,1,20240126,None
3172096,80147010,UL05,T642,Contract Issue,9000000.0,2023-05-31,2023-05-31,3600000.0,0.0,100.0,...,60078191,60078191,2023-05-31,2023-05-31,18.0,2023-05-31,2023-06-08,1,20240126,None