In [74]:
import numpy as np
import pandas as pd
import pyodbc as pyo
import sqlalchemy as sa
import numpy as np
import math
import datetime
import datetime as dt
#Kết nối SV_UAT (SQL_SV64)
connection_uri_UAT = (
    "mssql+pyodbc://PHLHCMHOPPBI02\PBIRS/PowerBI?driver=ODBC+Driver+17+for+SQL+Server"
)
conn = sa.create_engine(connection_uri_UAT)

<h3>1. Lấy bảng

In [32]:
cutoff = input("Nhập kỳ CUTOFF cuối tháng YYYYMMDD: ")

Nhập kỳ CUTOFF cuối tháng YYYYMMDD: 20230131

<h5>1.1 Lấy bảng AgentInfo

In [33]:
agent_query = f"""\n
SELECT * FROM [DPO].[Main_AGENT_INFO_DA_CUTOFF]
WHERE CUTOFF = {cutoff}
"""
agent_table = pd.read_sql(agent_query, conn)
agent_table

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,Leader,SFC,Leader_count,Appointed_TAPSU,CUTOFF,First_Appointed,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade
0,TAA,Ngô Anh Tài,AD082,60030650,DM - PHẠM THỊ CÚC HOA,60030655,FM - PHẠM THỊ HỒNG ANH,60060890,NGUYỄN HOÀNG ANH,Male,...,60030655,,2,2022-06-20,20230131,None,None,None,None,None
1,ABT,Nguyễn Thị Tố Quyên,AD786,60055833,FM - NGUYỄN NGỌC DUY QUANG,60055914,FM - HUỲNH THANH TUẤN,60060917,PHẠM BÁ KHƯƠNG,Male,...,60055914,,3,2022-06-20,20230131,None,None,None,None,None
2,EAK,Thiều Quang Mạnh,AD174,60008686,DM - NGUYỄN VĂN KỶ,60019636,FC - NGUYỄN THỊ NỤ,60021398,NGUYỄN THỊ MẬU,Female,...,60008686,,2,2019-06-19,20230131,None,None,None,None,None
3,AVP,Văn Hương Giang,AD811,,None,60054777,DM - ĐÀO THỊ NGA,60055999,NGUYỄN THỊ BIÊN,Female,...,60054777,,1,2022-01-25,20230131,None,None,None,None,None
4,LAK,Đặng Văn Phan,AD501,60062231,DM - PHAN HỮU SỸ,60075163,FM - ĐẶNG THỊ SOA,60075691,LÊ THỊ KHÁNH LY,Female,...,60075163,,6,2022-12-29,20230131,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75901,STR,Lục Minh Hiếu,AD409,60002305,FC - LÊ THÀNH DÂN,60000699,AM - TRƯƠNG HUY LUẬN,60006002,NGÔ QUỐC TRUNG,Male,...,None,,2,2016-09-26,20230131,None,None,None,None,None
75902,SG1,Lê Nguyễn Ánh Nguyệt,AD752,60070913,DM - NGUYỄN MINH TUẤN,60070705,FC - LÊ TRƯỜNG KHÁNH,60074423,PHAN THỊ TUYẾT HƯƠNG,Female,...,60070913,,6,2022-12-12,20230131,None,None,None,None,None
75903,BMT,Võ Tất Thắng,AD088,,None,60016183,FC - KIỀU THỊ MỸ LỘC,60016239,LÊ THỊ PHƯỚC,Female,...,None,,1,2018-08-24,20230131,None,None,None,None,None
75904,LAN,Trương Thái Tuấn,AD099,None,None,,None,60005479,HỒ NGỌC THÔNG,Male,...,None,,0,2016-08-25,20230131,None,None,None,None,None
75905,EAK,Lê Thị Hoài,AD680,60020362,RM - ĐỖ THỊ LOAN,60026999,FM - NGUYỄN THỊ NGOÃN,60042462,NGUYỄN THỊ XUÂN,Female,...,60026999,,2,2021-05-18,20230131,None,None,None,None,None

<h5>1.2 Lấy bảng PREMIUM

In [75]:
premium_query = f"""\n
SELECT * FROM [DPO].[DP_TAGENTPREMIUM_TEST_CUTOFF]
WHERE CUTOFF = {cutoff}
"""
premium_table = pd.read_sql(premium_query, conn)
premium_table

,Policy No,Product Code,Premium transaction,PREM TRAN NAME,Premium Collected,Collected Date,Applied Premium Date,FYP Before Discount,FYP Discount,FYP,...,Area Code,Servicing Agent,Freelook,Proposal Receive Date,RISK_COMMENCE_DATE,Age_Customer,Issuing Agent,AFYP,CUTOFF,RETURN_DATE
0,80000836,EN04,B522,Premium Collection,2133000.0,2018-10-13,2018-10-13,0.0,0.0,0.0,...,DR1,69999983,2660.0,2015-10-15,2015-10-13,53.0,69999982,7900000.0,20230131,None
1,80000836,EN04,B522,Premium Collection,2133000.0,2016-03-01,2016-03-01,2133000.0,0.0,2133000.0,...,DR1,69999982,2660.0,2015-10-15,2015-10-13,53.0,69999982,7900000.0,20230131,None
2,80000836,EN04,B522,Premium Collection,2133000.0,2017-01-13,2017-01-13,0.0,0.0,0.0,...,DR1,69999983,2660.0,2015-10-15,2015-10-13,53.0,69999982,7900000.0,20230131,None
3,80000836,EN04,B522,Premium Collection,2133000.0,2021-01-13,2021-01-13,0.0,0.0,0.0,...,DR1,69999998,2660.0,2015-10-15,2015-10-13,53.0,69999982,7900000.0,20230131,None
4,80000836,EN04,B522,Premium Collection,2133000.0,2019-10-13,2019-10-13,0.0,0.0,0.0,...,DR1,69999983,2660.0,2015-10-15,2015-10-13,53.0,69999982,7900000.0,20230131,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283630,80133071,RHS1,T642,Contract Issue,849000.0,2023-01-31,2023-01-31,849000.0,0.0,849000.0,...,DN1,60073330,0.0,2023-01-31,2023-01-31,43.0,60073330,8066000.0,20230131,None
1283631,80133071,URA5,T642,Contract Issue,537000.0,2023-01-31,2023-01-31,537000.0,0.0,537000.0,...,DN1,60073330,0.0,2023-01-31,2023-01-31,43.0,60073330,8066000.0,20230131,None
1283632,80133071,URC5,T642,Contract Issue,1080000.0,2023-01-31,2023-01-31,1080000.0,0.0,1080000.0,...,DN1,60073330,0.0,2023-01-31,2023-01-31,43.0,60073330,8066000.0,20230131,None
1283633,80133071,RHB1,T642,Contract Issue,600000.0,2023-01-31,2023-01-31,600000.0,0.0,600000.0,...,DN1,60073330,0.0,2023-01-31,2023-01-31,43.0,60073330,8066000.0,20230131,None
1283634,80133071,UL06,T642,Contract Issue,5000000.0,2023-01-31,2023-01-31,5000000.0,0.0,5000000.0,...,DN1,60073330,0.0,2023-01-31,2023-01-31,43.0,60073330,8066000.0,20230131,None

In [79]:
premium_table[premium_table['Servicing Agent'] == '60073734']

,Policy No,Product Code,Premium transaction,PREM TRAN NAME,Premium Collected,Collected Date,Applied Premium Date,FYP Before Discount,FYP Discount,FYP,...,Area Code,Servicing Agent,Freelook,Proposal Receive Date,RISK_COMMENCE_DATE,Age_Customer,Issuing Agent,AFYP,CUTOFF,RETURN_DATE
1036746,80127836,UL06,T642,Contract Issue,18324000.0,2022-12-12,2022-12-12,18324000.0,0.0,18324000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,32.0,60073734,18324000.0,20230131,None
1037679,80127790,RHB1,T642,Contract Issue,520000.0,2022-12-09,2022-12-09,520000.0,0.0,520000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,29.0,60073734,18004000.0,20230131,None
1037680,80127790,URC6,T642,Contract Issue,1076000.0,2022-12-09,2022-12-09,1076000.0,0.0,1076000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,29.0,60073734,18004000.0,20230131,None
1037681,80127790,UL06,T642,Contract Issue,14837000.0,2022-12-09,2022-12-09,14837000.0,0.0,14837000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,29.0,60073734,18004000.0,20230131,None
1037682,80127790,URA5,T642,Contract Issue,716000.0,2022-12-09,2022-12-09,716000.0,0.0,716000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,29.0,60073734,18004000.0,20230131,None
1037683,80127790,URC5,T642,Contract Issue,855000.0,2022-12-09,2022-12-09,855000.0,0.0,855000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,29.0,60073734,18004000.0,20230131,None
1040308,80127799,URC5,T642,Contract Issue,682000.0,2022-12-12,2022-12-12,682000.0,0.0,682000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,24.0,60073734,18484000.0,20230131,None
1040309,80127799,URA5,T642,Contract Issue,716000.0,2022-12-12,2022-12-12,716000.0,0.0,716000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,24.0,60073734,18484000.0,20230131,None
1040310,80127799,UL06,T642,Contract Issue,16606000.0,2022-12-12,2022-12-12,16606000.0,0.0,16606000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,24.0,60073734,18484000.0,20230131,None
1040311,80127799,RHB1,T642,Contract Issue,480000.0,2022-12-12,2022-12-12,480000.0,0.0,480000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,24.0,60073734,18484000.0,20230131,None
1040503,80127791,UL06,T642,Contract Issue,15194000.0,2022-12-09,2022-12-09,15194000.0,0.0,15194000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,26.0,60073734,18012000.0,20230131,None
1040504,80127791,URA5,T642,Contract Issue,1565000.0,2022-12-09,2022-12-09,1565000.0,0.0,1565000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,26.0,60073734,18012000.0,20230131,None
1040505,80127791,RHB1,T642,Contract Issue,520000.0,2022-12-09,2022-12-09,520000.0,0.0,520000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,26.0,60073734,18012000.0,20230131,None
1040506,80127791,URC5,T642,Contract Issue,733000.0,2022-12-09,2022-12-09,733000.0,0.0,733000.0,...,BH2,60073734,50.0,2022-12-09,2022-12-09,26.0,60073734,18012000.0,20230131,None
1054719,80127801,UL06,T642,Contract Issue,13332000.0,2022-12-12,2022-12-12,13332000.0,0.0,13332000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,18.0,60073734,16165000.0,20230131,None
1054720,80127801,RHB1,T642,Contract Issue,460000.0,2022-12-12,2022-12-12,460000.0,0.0,460000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,18.0,60073734,16165000.0,20230131,None
1054721,80127801,URC5,T642,Contract Issue,600000.0,2022-12-12,2022-12-12,600000.0,0.0,600000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,18.0,60073734,16165000.0,20230131,None
1054722,80127801,URA5,T642,Contract Issue,1074000.0,2022-12-12,2022-12-12,1074000.0,0.0,1074000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,18.0,60073734,16165000.0,20230131,None
1054723,80127801,URC6,T642,Contract Issue,699000.0,2022-12-12,2022-12-12,699000.0,0.0,699000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,18.0,60073734,16165000.0,20230131,None
1076787,80127806,UL06,T642,Contract Issue,14965000.0,2022-12-12,2022-12-12,14965000.0,0.0,14965000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,29.0,60073734,18010000.0,20230131,None
1076788,80127806,RHB1,T642,Contract Issue,520000.0,2022-12-12,2022-12-12,520000.0,0.0,520000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,29.0,60073734,18010000.0,20230131,None
1076789,80127806,URA5,T642,Contract Issue,1661000.0,2022-12-12,2022-12-12,1661000.0,0.0,1661000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,29.0,60073734,18010000.0,20230131,None
1076790,80127806,URC5,T642,Contract Issue,864000.0,2022-12-12,2022-12-12,864000.0,0.0,864000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,29.0,60073734,18010000.0,20230131,None
1263270,80127788,RHB1,T642,Contract Issue,480000.0,2022-12-09,2022-12-09,480000.0,0.0,480000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,23.0,60073734,18001000.0,20230131,None
1263271,80127788,UL06,T642,Contract Issue,15000000.0,2022-12-09,2022-12-09,15000000.0,0.0,15000000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,23.0,60073734,18001000.0,20230131,None
1263272,80127788,URA5,T642,Contract Issue,1074000.0,2022-12-09,2022-12-09,1074000.0,0.0,1074000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,23.0,60073734,18001000.0,20230131,None
1263273,80127788,URC5,T642,Contract Issue,540000.0,2022-12-09,2022-12-09,540000.0,0.0,540000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,23.0,60073734,18001000.0,20230131,None
1263274,80127788,URC6,T642,Contract Issue,907000.0,2022-12-09,2022-12-09,907000.0,0.0,907000.0,...,BH2,60073734,47.0,2022-12-09,2022-12-09,23.0,60073734,18001000.0,20230131,None
1265789,80132698,RHB1,T642,Contract Issue,800000.0,2023-01-30,2023-01-30,800000.0,0.0,800000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,46.0,60073734,40004000.0,20230131,None
1265790,80132698,UL06,T642,Contract Issue,34282000.0,2023-01-30,2023-01-30,34282000.0,0.0,34282000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,46.0,60073734,40004000.0,20230131,None
1265791,80132698,URC5,T642,Contract Issue,640000.0,2023-01-30,2023-01-30,640000.0,0.0,640000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,6.0,60073734,40004000.0,20230131,None
1265792,80132698,URC5,T642,Contract Issue,2295000.0,2023-01-30,2023-01-30,2295000.0,0.0,2295000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,46.0,60073734,40004000.0,20230131,None
1265793,80132698,URA5,T642,Contract Issue,1074000.0,2023-01-30,2023-01-30,1074000.0,0.0,1074000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,6.0,60073734,40004000.0,20230131,None
1265794,80132698,URA5,T642,Contract Issue,913000.0,2023-01-30,2023-01-30,913000.0,0.0,913000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,46.0,60073734,40004000.0,20230131,None
1277649,80132336,URC5,T642,Contract Issue,1005000.0,2023-01-27,2023-01-27,1005000.0,0.0,1005000.0,...,BH2,60073734,0.0,2023-01-27,2023-01-27,28.0,60073734,22000000.0,20230131,None
1278055,80132326,UL06,T642,Contract Issue,19851000.0,2023-01-27,2023-01-27,19851000.0,0.0,19851000.0,...,BH2,60073734,0.0,2023-01-27,2023-01-27,32.0,60073734,22006000.0,20230131,None
1278252,80132326,URC5,T642,Contract Issue,1029000.0,2023-01-27,2023-01-27,1029000.0,0.0,1029000.0,...,BH2,60073734,0.0,2023-01-27,2023-01-27,32.0,60073734,22006000.0,20230131,None
1278253,80132326,URA5,T642,Contract Issue,1126000.0,2023-01-27,2023-01-27,1126000.0,0.0,1126000.0,...,BH2,60073734,0.0,2023-01-27,2023-01-27,32.0,60073734,22006000.0,20230131,None
1279065,80132336,UL06,T642,Contract Issue,19306000.0,2023-01-27,2023-01-27,19306000.0,0.0,19306000.0,...,BH2,60073734,0.0,2023-01-27,2023-01-27,28.0,60073734,22000000.0,20230131,None
1281516,80132336,URA5,T642,Contract Issue,1689000.0,2023-01-27,2023-01-27,1689000.0,0.0,1689000.0,...,BH2,60073734,0.0,2023-01-27,2023-01-27,28.0,60073734,22000000.0,20230131,None
1281825,80132692,UL06,T642,Contract Issue,27000000.0,2023-01-30,2023-01-30,27000000.0,0.0,27000000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,38.0,60073734,36002000.0,20230131,None
1281826,80132692,URA5,T642,Contract Issue,1790000.0,2023-01-30,2023-01-30,1790000.0,0.0,1790000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,4.0,60073734,36002000.0,20230131,None
1281827,80132692,URC6,T642,Contract Issue,2310000.0,2023-01-30,2023-01-30,2310000.0,0.0,2310000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,38.0,60073734,36002000.0,20230131,None
1281828,80132692,RHB1,T642,Contract Issue,600000.0,2023-01-30,2023-01-30,600000.0,0.0,600000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,4.0,60073734,36002000.0,20230131,None
1281829,80132692,URC5,T642,Contract Issue,640000.0,2023-01-30,2023-01-30,640000.0,0.0,640000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,4.0,60073734,36002000.0,20230131,None
1281830,80132692,URC5,T642,Contract Issue,1508000.0,2023-01-30,2023-01-30,1508000.0,0.0,1508000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,38.0,60073734,36002000.0,20230131,None
1281831,80132692,RHB1,T642,Contract Issue,1080000.0,2023-01-30,2023-01-30,1080000.0,0.0,1080000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,38.0,60073734,36002000.0,20230131,None
1281832,80132692,URA5,T642,Contract Issue,1074000.0,2023-01-30,2023-01-30,1074000.0,0.0,1074000.0,...,BH2,60073734,0.0,2023-01-30,2023-01-30,38.0,60073734,36002000.0,20230131,None

<h3>2. Lấy ra ngày xét

In [35]:
agent_t = agent_table

In [36]:
agent_t['Date_On_Set'] = pd.to_datetime(agent_t['CUTOFF'].str[:4]+"-"+agent_t['CUTOFF'].str[4:6]+"-"+agent_t['CUTOFF'].str[6:])
#Lấy ngày xét tạm:
#Rule: Join sau ngày 10 hàng tháng, tính sang tháng sau:
agent_t['Date_1st_Temp'] = np.where(agent_t['Date_Appointed'].dt.day > 10, 
        agent_t['Date_Appointed'] + pd.DateOffset(months=1), agent_t['Date_Appointed'])
agent_t['Date_1st_Temp'] = agent_t['Date_1st_Temp'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
agent_t['1st_month'] = agent_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1) - pd.DateOffset(months=2)
agent_t['2nd_month'] = agent_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1) - pd.DateOffset(months=1)
agent_t['3rd_month'] = agent_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
agent_t

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,First_Appointed,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month
0,TAA,Ngô Anh Tài,AD082,60030650,DM - PHẠM THỊ CÚC HOA,60030655,FM - PHẠM THỊ HỒNG ANH,60060890,NGUYỄN HOÀNG ANH,Male,...,None,None,None,None,None,2023-01-31,2022-07-01,2022-11-01,2022-12-01,2023-01-01
1,ABT,Nguyễn Thị Tố Quyên,AD786,60055833,FM - NGUYỄN NGỌC DUY QUANG,60055914,FM - HUỲNH THANH TUẤN,60060917,PHẠM BÁ KHƯƠNG,Male,...,None,None,None,None,None,2023-01-31,2022-07-01,2022-11-01,2022-12-01,2023-01-01
2,EAK,Thiều Quang Mạnh,AD174,60008686,DM - NGUYỄN VĂN KỶ,60019636,FC - NGUYỄN THỊ NỤ,60021398,NGUYỄN THỊ MẬU,Female,...,None,None,None,None,None,2023-01-31,2019-07-01,2022-11-01,2022-12-01,2023-01-01
3,AVP,Văn Hương Giang,AD811,,None,60054777,DM - ĐÀO THỊ NGA,60055999,NGUYỄN THỊ BIÊN,Female,...,None,None,None,None,None,2023-01-31,2022-02-01,2022-11-01,2022-12-01,2023-01-01
4,LAK,Đặng Văn Phan,AD501,60062231,DM - PHAN HỮU SỸ,60075163,FM - ĐẶNG THỊ SOA,60075691,LÊ THỊ KHÁNH LY,Female,...,None,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75901,STR,Lục Minh Hiếu,AD409,60002305,FC - LÊ THÀNH DÂN,60000699,AM - TRƯƠNG HUY LUẬN,60006002,NGÔ QUỐC TRUNG,Male,...,None,None,None,None,None,2023-01-31,2016-10-01,2022-11-01,2022-12-01,2023-01-01
75902,SG1,Lê Nguyễn Ánh Nguyệt,AD752,60070913,DM - NGUYỄN MINH TUẤN,60070705,FC - LÊ TRƯỜNG KHÁNH,60074423,PHAN THỊ TUYẾT HƯƠNG,Female,...,None,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01
75903,BMT,Võ Tất Thắng,AD088,,None,60016183,FC - KIỀU THỊ MỸ LỘC,60016239,LÊ THỊ PHƯỚC,Female,...,None,None,None,None,None,2023-01-31,2018-09-01,2022-11-01,2022-12-01,2023-01-01
75904,LAN,Trương Thái Tuấn,AD099,None,None,,None,60005479,HỒ NGỌC THÔNG,Male,...,None,None,None,None,None,2023-01-31,2016-09-01,2022-11-01,2022-12-01,2023-01-01
75905,EAK,Lê Thị Hoài,AD680,60020362,RM - ĐỖ THỊ LOAN,60026999,FM - NGUYỄN THỊ NGOÃN,60042462,NGUYỄN THỊ XUÂN,Female,...,None,None,None,None,None,2023-01-31,2021-07-01,2022-11-01,2022-12-01,2023-01-01

<h5>2.1 Lấy ra ngày cần xét trong 3 tháng gia nhập gần nhất

In [37]:
agent_rookie = agent_t[(agent_t['Date_1st_Temp'] >= agent_t['1st_month']) & (agent_t['Date_1st_Temp'] <= agent_t['Date_On_Set'])]
agent_rookie['Rookie_Month'] = np.where(agent_rookie['Date_1st_Temp'] == agent_rookie['3rd_month'], "1",
                            np.where(agent_rookie['Date_1st_Temp'] == agent_rookie['2nd_month'], "2",
                            "3"))
agent_rookie

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_12400\1443559686.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_rookie['Rookie_Month'] = np.where(agent_rookie['Date_1st_Temp'] == agent_rookie['3rd_month'], "1",

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month
4,LAK,Đặng Văn Phan,AD501,60062231,DM - PHAN HỮU SỸ,60075163,FM - ĐẶNG THỊ SOA,60075691,LÊ THỊ KHÁNH LY,Female,...,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1
7,AHD,AG Lê Thị Hường,AD931,None,None,,None,60073816,DUMMY VŨ THỊ MẬN,Female,...,None,None,None,None,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2
42,SG1,Lê Nguyễn Ánh Nguyệt,AD752,60056998,DM - NGUYỄN HỒNG BẢO NGỌC,60056999,FM - NGUYỄN MAI CHÍ TẤN,60074360,NGUYỄN TUẤN ANH,Male,...,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1
46,BH2,Nguyễn Thị Hòa,AD712,60041146,DM - NGUYỄN THỊ NGỌC NGA,60069291,DM - NGÔ THỊ ANH ĐÀO,60073691,TRẦN TIN,Male,...,None,None,None,None,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2
70,ASL,AG Bùi Văn Phương,AD942,,None,60027584,FC - CÀ THỊ HOÀN,60074404,CÀ THỊ BÍNH,Female,...,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75857,SG1,Huỳnh Phạm Đăng Khánh,AD623,60055933,DM - NGUYỄN THÀNH CÔNG,60055935,FM - LỤC HOÀI BẢO,60072970,LƯU ĐÔNG THÀNH,Male,...,None,None,None,None,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2
75863,AHP,Nguyễn Văn Thành,AD585,60073785,DM - NGUYỄN THỊ HẢI,60073438,FM - ĐẶNG QUANG DŨNG,60072504,NGUYỄN NGỌC NGHĨA,Male,...,None,None,None,None,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2
75872,SG1,Lê Nguyễn Ánh Nguyệt,AD752,60057048,FM - NGUYỄN THỊ KIM ANH,60057050,FM - NGUYỄN NGỌC LAN,60074163,NGÔ QUANG TUYẾN,Male,...,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1
75891,RGI,Nguyễn Thành Trung,AD852,60067323,DM - TRẦN THANH THẬT,60071329,DM - TRẦN THỊ LƯỢM,60071377,HÀ SƠN NHẬT,Male,...,None,None,None,None,2023-01-31,2022-11-01,2022-11-01,2022-12-01,2023-01-01,3
75902,SG1,Lê Nguyễn Ánh Nguyệt,AD752,60070913,DM - NGUYỄN MINH TUẤN,60070705,FC - LÊ TRƯỜNG KHÁNH,60074423,PHAN THỊ TUYẾT HƯƠNG,Female,...,None,None,None,None,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1

<h5>2.2 Set Target FYP và CC:

In [39]:
agent_target = agent_rookie
agent_target['FYPTargetCatchup'] = np.where(agent_target['Rookie_Month'] == '3', 72000000,
                       np.where(agent_target['Rookie_Month'] == '2', 48000000,
                      np.where(agent_target['Rookie_Month'] == '1', 24000000, 0)))
agent_target['CCTargetCatchup'] = np.where(agent_target['Rookie_Month'] == '3', 6,
                       np.where(agent_target['Rookie_Month'] == '2', 4,
                      np.where(agent_target['Rookie_Month'] == '1', 2, 0)))
agent_target['FYP Target'] = 24000000
agent_target['CC Target'] = 2

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_12400\2756237256.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_target['FYPTargetCatchup'] = np.where(agent_target['Rookie_Month'] == '3', 72000000,
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_12400\2756237256.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_target['CCTargetCatchup'] = np.where(agent_target['Rookie_Month'] == '3', 6,
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_12400\2756237256.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_target['FYP Target'] = 24000000
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_12400\2756237256.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_target['CC Target'] = 2

In [40]:
agent_target = agent_target[['Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'Agent_Number', 'Agent_Name', 'Grade', 
         'Agent_Status', 'Date_Appointed', 'CUTOFF', 'Date_On_Set', 'Date_1st_Temp', 
        '1st_month', '2nd_month', '3rd_month', 'Rookie_Month','FYP Target', 'CC Target', 'FYPTargetCatchup', 'CCTargetCatchup']]
agent_target

,Area_Name,Sales_Unit_Code,Sales_Unit,Agent_Number,Agent_Name,Grade,Agent_Status,Date_Appointed,CUTOFF,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month,FYP Target,CC Target,FYPTargetCatchup,CCTargetCatchup
4,LAK,AD501,Đặng Văn Phan,60075691,LÊ THỊ KHÁNH LY,FC,Enforce,2022-12-29,20230131,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,24000000,2,24000000,2
7,AHD,AD931,AG Lê Thị Hường,60073816,DUMMY VŨ THỊ MẬN,DM,Enforce,2022-11-29,20230131,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,24000000,2,48000000,4
42,SG1,AD752,Lê Nguyễn Ánh Nguyệt,60074360,NGUYỄN TUẤN ANH,FC,Enforce,2022-12-12,20230131,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,24000000,2,24000000,2
46,BH2,AD712,Nguyễn Thị Hòa,60073691,TRẦN TIN,FC,Enforce,2022-11-28,20230131,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,24000000,2,48000000,4
70,ASL,AD942,AG Bùi Văn Phương,60074404,CÀ THỊ BÍNH,FC,Enforce,2022-12-14,20230131,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,24000000,2,24000000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75857,SG1,AD623,Huỳnh Phạm Đăng Khánh,60072970,LƯU ĐÔNG THÀNH,FC,Enforce,2022-11-21,20230131,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,24000000,2,48000000,4
75863,AHP,AD585,Nguyễn Văn Thành,60072504,NGUYỄN NGỌC NGHĨA,FC,Enforce,2022-11-29,20230131,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,24000000,2,48000000,4
75872,SG1,AD752,Lê Nguyễn Ánh Nguyệt,60074163,NGÔ QUANG TUYẾN,FC,Enforce,2022-12-12,20230131,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,24000000,2,24000000,2
75891,RGI,AD852,Nguyễn Thành Trung,60071377,HÀ SƠN NHẬT,FM,Enforce,2022-10-25,20230131,2023-01-31,2022-11-01,2022-11-01,2022-12-01,2023-01-01,3,24000000,2,72000000,6
75902,SG1,AD752,Lê Nguyễn Ánh Nguyệt,60074423,PHAN THỊ TUYẾT HƯƠNG,FC,Enforce,2022-12-12,20230131,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,24000000,2,24000000,2

<h3> 3. Tính FYP

In [109]:
fyp_cal = premium_table
fyp_cal = fyp_cal[['Servicing Agent', 'Applied Premium Date', 'POLICY ACKNOWLED', 'Policy Status','Freelook' ,'FYP', 'Topup Premium']]
fyp_cal['FYP_Total'] = fyp_cal['FYP'] + fyp_cal['Topup Premium']*0.1
fyp_cal = fyp_cal.groupby(['Servicing Agent', 'Applied Premium Date', 'POLICY ACKNOWLED', 'Policy Status', 'Freelook'], dropna=False)['FYP_Total'].sum().reset_index()
fyp_cal = fyp_cal[~fyp_cal['Policy Status'].isin(['CF', 'DC', 'FL',  'NT', 'WD', 'PO'])]
fyp_cal

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_12400\91385868.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fyp_cal['FYP_Total'] = fyp_cal['FYP'] + fyp_cal['Topup Premium']*0.1

,Servicing Agent,Applied Premium Date,POLICY ACKNOWLED,Policy Status,Freelook,FYP_Total
0,60000002,2014-07-21,2014-08-13,LA,3094.0,5088000.0
1,60000002,2015-06-21,2014-08-13,LA,3094.0,0.0
2,60000003,2014-05-30,2014-06-04,LA,3164.0,4500000.0
3,60000003,2014-06-16,2014-06-17,LA,3151.0,2815000.0
4,60000003,2014-06-30,2014-07-07,LA,3131.0,2518000.0
...,...,...,...,...,...,...
264713,69999999,2022-11-29,2015-10-05,IF,2676.0,0.0
264714,69999999,2022-12-07,2014-12-05,IF,2980.0,0.0
264715,69999999,2022-12-14,2014-10-30,IF,3016.0,0.0
264716,69999999,2022-12-14,2015-02-11,IF,2912.0,0.0
264717,69999999,2022-12-19,2014-11-05,IF,3010.0,0.0

<h5>3.1 Lọc các dòng FYP được tính

In [110]:
fyp_date = pd.merge(fyp_cal, agent_target, left_on = 'Servicing Agent', right_on ='Agent_Number', how = 'left')
fyp_date = fyp_date[(fyp_date['Applied Premium Date']>=fyp_date['Date_Appointed']) & (fyp_date['Applied Premium Date']<=fyp_date['Date_On_Set'])]
fyp_date = fyp_date[['Servicing Agent', 'Applied Premium Date', 'POLICY ACKNOWLED',
       'Policy Status', 'Freelook','FYP_Total', 'Date_On_Set', 'Date_1st_Temp', '1st_month', '2nd_month', '3rd_month', 'Rookie_Month']]
fyp_date['Applied_Temp'] = fyp_date['Applied Premium Date'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
fyp_date['ACK_Temp'] = fyp_date['POLICY ACKNOWLED'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
fyp_date

,Servicing Agent,Applied Premium Date,POLICY ACKNOWLED,Policy Status,Freelook,FYP_Total,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month,Applied_Temp,ACK_Temp
27753,60006754,2022-11-29,2022-12-06,IF,57.0,20075000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-11-01,2022-12-01
27754,60006754,2022-12-13,2022-12-19,IF,44.0,8058000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-12-01,2022-12-01
27755,60006754,2023-01-27,NaT,IF,0.0,16595000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2023-01-01,NaT
28005,60006841,2022-10-31,2022-11-10,IF,83.0,13646000.0,2023-01-31,2022-11-01,2022-11-01,2022-12-01,2023-01-01,3,2022-10-01,2022-11-01
31598,60007707,2022-10-21,2022-10-30,IF,94.0,25053000.0,2023-01-31,2022-11-01,2022-11-01,2022-12-01,2023-01-01,3,2022-10-01,2022-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248087,60075882,2023-01-17,2023-01-18,IF,14.0,8000000.0,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,2023-01-01,2023-01-01
248089,60075885,2023-01-11,2023-01-16,IF,16.0,75158000.0,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,2023-01-01,2023-01-01
248090,60075885,2023-01-16,2023-01-30,IF,2.0,30001000.0,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,2023-01-01,2023-01-01
248091,60075885,2023-01-31,NaT,IF,0.0,22938000.0,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,2023-01-01,NaT
248093,60075887,2023-01-17,2023-01-30,IF,2.0,15006000.0,2023-01-31,2023-01-01,2022-11-01,2022-12-01,2023-01-01,1,2023-01-01,2023-01-01

In [120]:
fyp_date.to_csv('checktemp1.csv')

<h5>3.2 Tổng lấy FYP 3 tháng (tạm tính)

In [121]:
##BƯỚC NÀY: PHÂN RA CÁC FYP:
fyp_date['FYP_month'] = np.where(fyp_date['Applied_Temp'] == fyp_date['1st_month'], "FYP(T-2)",
                    np.where(fyp_date['Applied_Temp'] == fyp_date['2nd_month'], "FYP(T-1)",
                    np.where(fyp_date['Applied_Temp'] == fyp_date['3rd_month'], "FYP_Current(T)", "FYP(T-2)")))
fyp_date['FYP_P_month'] = np.where(fyp_date['ACK_Temp'] == fyp_date['1st_month'], "FYP_P(T-2)",
                    np.where(fyp_date['ACK_Temp'] == fyp_date['2nd_month'], "FYP_P(T-1)",
                    np.where(fyp_date['ACK_Temp'] == fyp_date['3rd_month'], "FYP_PCurrent(T)", "")))
#Note ở, bước(T-2) sau cùng, thì các TH Applied rơi vào tháng trước 1st, thì sẽ rơi vào tháng T-2 để xét
fyp_pivot = fyp_date.groupby(['Servicing Agent', 'FYP_month'], dropna=False)['FYP_Total'].sum().reset_index()
fyp_cal = fyp_pivot.pivot(index='Servicing Agent', columns='FYP_month', values='FYP_Total').reset_index()
fyp_cal

FYP_month Servicing Agent    FYP(T-1)    FYP(T-2)  FYP_Current(T)
0                60006754   8058000.0  20075000.0      16595000.0
1                60006841         NaN  13646000.0             NaN
2                60007707         NaN  25053000.0             0.0
3                60009490  49251000.0         NaN      22064000.0
4                60012017         NaN  20160000.0             NaN
...                   ...         ...         ...             ...
1389             60075880         NaN         NaN      22029000.0
1390             60075881         NaN         NaN       8000000.0
1391             60075882         NaN         NaN       8000000.0
1392             60075885         NaN         NaN     128097000.0
1393             60075887         NaN         NaN      15006000.0

[1394 rows x 4 columns]

In [125]:
fyp_cal.to_csv('checkfyptemp.csv')

<h5>3.3 Tổng lấy FYP thực đạt (Đã pass FL 21 ngày)

In [123]:
fyp_pivot_1 = fyp_date[fyp_date['FYP_P_month']!=''].groupby(['Servicing Agent', 'FYP_P_month'], dropna=False)['FYP_Total'].sum().reset_index()
fyp_paid = fyp_pivot_1.pivot(index='Servicing Agent', columns='FYP_P_month', values='FYP_Total').reset_index()
fyp_paid

FYP_P_month Servicing Agent  FYP_P(T-1)  FYP_P(T-2)  FYP_PCurrent(T)
0                  60006754  28133000.0         NaN              NaN
1                  60006841         NaN  13646000.0              NaN
2                  60009490  49251000.0         NaN              NaN
3                  60012017         NaN  20160000.0              NaN
4                  60012461  27479000.0  18245000.0              NaN
...                     ...         ...         ...              ...
1244               60075877         NaN         NaN       30017000.0
1245               60075881         NaN         NaN        8000000.0
1246               60075882         NaN         NaN        8000000.0
1247               60075885         NaN         NaN      105159000.0
1248               60075887         NaN         NaN       15006000.0

[1249 rows x 4 columns]

<h5>3.4 Lấy FYP thực đạt trong tháng xét

In [129]:
fyp_within_month = fyp_date
fyp_within_month['FYP_Monthly_Achieved'] = np.where(fyp_within_month['Freelook'] >21, 
    fyp_within_month['FYP_Total'],0)
fyp_within_month[fyp_within_month['Servicing Agent'] == '60073218']

,Servicing Agent,Applied Premium Date,POLICY ACKNOWLED,Policy Status,Freelook,FYP_Total,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month,Applied_Temp,ACK_Temp,FYP_month,FYP_P_month,FYP_Monthly_Achieved
246990,60073218,2022-11-29,2022-12-14,IF,49.0,10646000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-11-01,2022-12-01,FYP(T-2),FYP_P(T-1),10646000.0
246991,60073218,2022-11-30,2022-12-14,IF,49.0,42047000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-11-01,2022-12-01,FYP(T-2),FYP_P(T-1),42047000.0
246992,60073218,2022-12-27,2023-01-15,IF,17.0,38531000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-12-01,2023-01-01,FYP(T-1),FYP_PCurrent(T),0.0
246993,60073218,2022-12-30,2023-01-15,IF,17.0,28016000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-12-01,2023-01-01,FYP(T-1),FYP_PCurrent(T),0.0
246994,60073218,2022-12-31,2023-01-15,IF,17.0,15467000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2022-12-01,2023-01-01,FYP(T-1),FYP_PCurrent(T),0.0
246995,60073218,2023-01-10,NaT,IF,0.0,16400000.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2023-01-01,NaT,FYP_Current(T),,0.0
246996,60073218,2023-01-31,NaT,IF,0.0,47200.0,2023-01-31,2022-12-01,2022-11-01,2022-12-01,2023-01-01,2,2023-01-01,NaT,FYP_Current(T),,0.0

<h3> 4. Tính CaseCount

In [107]:
cc_agent = premium_table
cc_agent = cc_agent[['Policy No', 'PREM TRAN NAME', 'Applied Premium Date', 'POLICY ACKNOWLED', 'Issuing Agent', 'Freelook', 'Policy Status']].drop_duplicates()
cc_agent['PREM TRAN NAME'] = cc_agent['PREM TRAN NAME'].str.strip()
cc_agent = cc_agent[(cc_agent['PREM TRAN NAME'] == 'Contract Issue') & (cc_agent['Freelook'] > 21) &
            ~cc_agent['Policy Status'].isin(['CF', 'DC', 'FL',  'NT', 'WD', 'PO'])]
cc_agent

,Policy No,PREM TRAN NAME,Applied Premium Date,POLICY ACKNOWLED,Issuing Agent,Freelook,Policy Status
11,80002938,Contract Issue,2016-04-29,2016-05-07,60002527,2520.0,IF
25,80002939,Contract Issue,2016-04-29,2016-05-07,60003239,2520.0,LA
28,80002940,Contract Issue,2016-04-29,2016-05-04,60000879,2523.0,SU
115,80000584,Contract Issue,2015-08-27,2015-08-29,60000163,2772.0,IF
122,80001483,Contract Issue,2015-12-30,2016-01-07,60000682,2641.0,LA
...,...,...,...,...,...,...,...
1351364,80004872,Contract Issue,2016-08-23,2016-08-28,60004021,2407.0,IF
1351386,80004873,Contract Issue,2016-08-23,2016-08-25,60001823,2410.0,LA
1351387,80004874,Contract Issue,2016-08-23,2016-08-25,60004952,2410.0,LA
1351388,80004875,Contract Issue,2016-08-23,2016-08-25,60005250,2410.0,LA
1351431,80004825,Contract Issue,2016-08-18,2016-08-23,60005210,2412.0,IF

<h5> 4.1 Lọc ra các ngày trong kỳ tính toán:

In [115]:
cc_cal = pd.merge(cc_agent, agent_target, left_on = 'Issuing Agent', right_on ='Agent_Number', how = 'left')
cc_cal = cc_cal[['Policy No', 'PREM TRAN NAME', 'Applied Premium Date',
       'POLICY ACKNOWLED', 'Issuing Agent', 'Date_Appointed' ,'Freelook', 'Policy Status', 'Date_On_Set', 'Date_1st_Temp', '1st_month', '2nd_month', '3rd_month']]
cc_cal['Applied_Temp'] = cc_cal['POLICY ACKNOWLED'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
cc_cal = cc_cal[(cc_cal['POLICY ACKNOWLED'] >= cc_cal['Date_Appointed']) & (cc_cal['POLICY ACKNOWLED'] <= cc_cal['Date_On_Set'])]
cc_cal['CC_Month'] = np.where(cc_cal['Applied_Temp']<=cc_cal['1st_month'], "3",
                    np.where(cc_cal['Applied_Temp'] == cc_cal['2nd_month'], "2",
                    np.where(cc_cal['Applied_Temp'] == cc_cal['3rd_month'], "1", "")))
cc_cal = cc_cal[['Issuing Agent', 'Policy No', 'POLICY ACKNOWLED', 'CC_Month']].drop_duplicates()
cc_cal = cc_cal.groupby(['Issuing Agent', 'CC_Month'])['Policy No'].count().reset_index()
cc_cal = cc_cal.pivot(index='Issuing Agent', columns='CC_Month', values ='Policy No').reset_index()
cc_cal = cc_cal.rename(columns={'1':'CC_1st', '2': 'CC_2nd', '3':'CC_3rd'})
cc_cal

CC_Month Issuing Agent  CC_1st  CC_2nd  CC_3rd
0             60005807     1.0     3.0     NaN
1             60007436     NaN     2.0     NaN
2             60007949     1.0     3.0     NaN
3             60009490     NaN     2.0     2.0
4             60010010     NaN     4.0     NaN
...                ...     ...     ...     ...
1032          60077049     2.0     NaN     NaN
1033          60077055     1.0     NaN     NaN
1034          60077057     3.0     NaN     NaN
1035          60077084     3.0     NaN     NaN
1036          60077099     1.0     NaN     NaN

[1037 rows x 4 columns]

<h3> 5. Ghép lại thông tin

In [149]:
agent_rookie_bonus = pd.merge(pd.merge(agent_target, fyp_pivot, left_on = 'Agent_Number', right_on ='Servicing Agent', how = 'left'), 
        cc_cal, left_on ='Agent_Number', right_on = 'Issuing Agent', how='left')
rookie_bonus = agent_rookie_bonus[['Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'Agent_Number',
       'Agent_Name', 'Grade', 'Agent_Status', 'Date_Appointed', 'CUTOFF',
       'Date_On_Set', 'Date_1st_Temp', '1st_month', '2nd_month', '3rd_month',
       'Rookie_Month', 'FYP Target', 'CC Target', 'FYP_1st', 'FYP_2nd', 'FYP_3rd', 'CC_1st', 'CC_2nd', 'CC_3rd']]
for i in ['FYP_1st', 'FYP_2nd', 'FYP_3rd', 'CC_1st', 'CC_2nd', 'CC_3rd']:
    rookie_bonus[i] = rookie_bonus[i].fillna(0)
rookie_bonus['FYP_3month_CatchUp'] = rookie_bonus['FYP_1st'] + rookie_bonus['FYP_2nd'] + rookie_bonus['FYP_3rd']
rookie_bonus['FYP_2month_CatchUp'] = rookie_bonus['FYP_1st'] + rookie_bonus['FYP_2nd'] + rookie_bonus['FYP_3rd']
rookie_bonus['CC_3month_CatchUp'] = rookie_bonus['CC_1st'] + rookie_bonus['CC_2nd'] + rookie_bonus['CC_3rd']
rookie_bonus['CC_2month_CatchUp'] = rookie_bonus['CC_1st'] + rookie_bonus['CC_2nd'] + rookie_bonus['CC_3rd']
#
rookie_bonus['CC_1st'] = np.where((rookie_bonus['Rookie_Month'] == '1'),
rookie_bonus['CC_1st'] + rookie_bonus['CC_2nd'],0)
#
rookie_bonus['FYP_1st'] = np.where((rookie_bonus['Rookie_Month'] == '1'),
rookie_bonus['FYP_1st'] + rookie_bonus['FYP_2nd'],0)
#
rookie_bonus = rookie_bonus.rename(columns={'FYP_1st': 'FYP_Cur_Mth(T)', 'FYP_2nd': 'FYP(T-1)', 'FYP_3rd':'FYP(T-2)',
                                    'CC_1st': 'CC_Cur_Mth(T)', 'CC_2nd': 'CC(T-1)', 'CC_3rd':'CC(T-2)'})
rookie_bonus = rookie_bonus[['Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'Agent_Number',
       'Agent_Name', 'Grade', 'Agent_Status', 'Date_Appointed', 'CUTOFF',
       'Rookie_Month', 'FYP Target', 'CC Target', 'FYP_Cur_Mth(T)', 'FYP(T-1)','FYP(T-2)', 'FYP_2month_CatchUp', 'FYP_3month_CatchUp',
        'CC_Cur_Mth(T)', 'CC(T-1)', 'CC(T-2)', 'CC_2month_CatchUp', 'CC_3month_CatchUp']]
rookie_bonus

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\3355310647.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rookie_bonus[i] = rookie_bonus[i].fillna(0)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\3355310647.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rookie_bonus['FYP_3month_CatchUp'] = rookie_bonus['FYP_1st'] + rookie_bonus['FYP_2nd'] + rookie_bonus['FYP_3rd']

,Area_Name,Sales_Unit_Code,Sales_Unit,Agent_Number,Agent_Name,Grade,Agent_Status,Date_Appointed,CUTOFF,Rookie_Month,...,FYP_Cur_Mth(T),FYP(T-1),FYP(T-2),FYP_2month_CatchUp,FYP_3month_CatchUp,CC_Cur_Mth(T),CC(T-1),CC(T-2),CC_2month_CatchUp,CC_3month_CatchUp
0,AHL,AD642,Nguyễn Thị Hồng,60074670,TRẦN THỊ HOÀI ANH,FC,Enforce,2022-12-26,20230331,3,...,0.0,0.0,24609000.0,24609000.0,24609000.0,0.0,0.0,2.0,2.0,2.0
1,AHN,AD840,AG Bùi Thị Bích Ngọc,60075282,HOÀNG THỊ HOA,FC,Enforce,2022-12-23,20230331,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AHN,AD840,AG Bùi Thị Bích Ngọc,60075362,ĐỖ HUY THẮNG,FM,Enforce,2022-12-24,20230331,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ACM,AD457,Phạm Phương Liên,60075425,NGUYỄN VĂN HÓA,FC,Enforce,2022-12-28,20230331,3,...,0.0,28682000.0,36111000.0,64793000.0,64793000.0,0.0,2.0,2.0,4.0,4.0
4,AHP,AD747,AG Lê Minh Tuấn,60074460,ĐỖ MẠNH THẮNG,FC,Enforce,2022-12-15,20230331,3,...,0.0,0.0,13163000.0,13163000.0,13163000.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,YTH,AD966,Hoàng Thị Luân,60074521,DUMMY LÔ THỊ QUÀNH,FM,Enforce,2022-12-13,20230331,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3117,YTH,AD966,Hoàng Thị Luân,60074523,DUMMY VI THỊ NGA,FM,Enforce,2022-12-13,20230331,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3118,YTH,AD966,Hoàng Thị Luân,60077034,ĐINH VIẾT LONG,FM,Enforce,2023-03-07,20230331,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3119,YTH,A1057,Ngô Thị Liên,60077150,DUMMY NGUYỄN THỊ YẾN,DM,Enforce,2023-03-08,20230331,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3120,ABL,AD329,Trần Hữu Nghị,60072139,TRẦN QUỐC THÁI,FC,Enforce,2022-12-31,20230331,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [154]:
rookie_bonus['Bonus'] = \
np.where((rookie_bonus['Rookie_Month'] == '1') & (rookie_bonus['FYP_Cur_Mth(T)'] >= rookie_bonus['FYP Target']) 
& (rookie_bonus['CC_Cur_Mth(T)'] >= rookie_bonus['CC Target']), 1000000,
##Xét các TH đã đạt trước:
np.where((rookie_bonus['Rookie_Month'] == '3') & (rookie_bonus['FYP_2month_CatchUp'] >= 48000000) &
(rookie_bonus['CC_2month_CatchUp'] >=4) & rookie_bonus[''], 0,
np.where((rookie_bonus['Rookie_Month'] == '2') & (rookie_bonus['FYP_2month_CatchUp'] >= 48000000) &
(rookie_bonus['CC_2month_CatchUp'] >=4),

In [155]:
rookie_bonus.to_csv('checkrookie.csv')

In [152]:
rookie_bonus.columns

Index(['Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'Agent_Number',
       'Agent_Name', 'Grade', 'Agent_Status', 'Date_Appointed', 'CUTOFF',
       'Rookie_Month', 'FYP Target', 'CC Target', 'FYP_Cur_Mth(T)', 'FYP(T-1)',
       'FYP(T-2)', 'FYP_2month_CatchUp', 'FYP_3month_CatchUp', 'CC_Cur_Mth(T)',
       'CC(T-1)', 'CC(T-2)', 'CC_2month_CatchUp', 'CC_3month_CatchUp'],
      dtype='object')