In [1]:
import numpy as np
import pandas as pd
import pyodbc as pyo
import sqlalchemy as sa
import numpy as np
import math
import datetime
import datetime as dt
from datetime import timedelta
#Kết nối SV_UAT (SQL_SV64)
connection_uri_UAT = (
    "mssql+pyodbc://PHLHCMHOPPBI02\PBIRS/PowerBI?driver=ODBC+Driver+17+for+SQL+Server"
)
conn = sa.create_engine(connection_uri_UAT)

<h3> 1. Lấy bảng

<h5>1.1. Lấy bảng AgentInfo

In [2]:
cutoff = input("Nhập kỳ CUTOFF cuối tháng YYYYMMDD: ")

Nhập kỳ CUTOFF cuối tháng YYYYMMDD: 20240126

In [4]:
agent_query = f"""\n
SELECT * FROM [DPO].[Main_AGENT_INFO_DA_CUTOFF]
WHERE CUTOFF = {cutoff}
"""
agent_table = pd.read_sql(agent_query, conn)
agent_table

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,Leader,SFC,Leader_count,Appointed_TAPSU,CUTOFF,First_Appointed,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade
0,DR1,Lưu Hoàng Thiện,AD018,None,None,,None,69999988,Bảo hiểm nhân thọ Phú Hưng,Male,...,None,,0,2014-10-15,20240126,2014-10-15,Direct Sales,None,None,None
1,DR1,Nguyễn Thị Thanh Loan (TER),AD049,None,None,,None,69999966,Bảo hiểm nhân thọ Phú Hưng,Female,...,None,,0,2015-10-29,20240126,2015-10-29,Direct Sales,None,None,None
2,HLO,Not Assigned,ADNUL,,None,60013747,FM - ĐẶNG LONG TÂN,60016738,NGUYỄN VĂN HIỀN,Male,...,60013747,,1,2018-09-20,20240126,2018-09-20,Ha Long,None,None,None
3,HLO,Not Assigned,ADNUL,,None,60015473,FM - VŨ THỊ THÀ,60019723,LÊ VĂN HIỀN,Male,...,None,,1,2019-03-01,20240126,2019-03-01,Ha Long,None,None,None
4,DR1,Đinh Hoàng Minh Diễm,AD013,None,None,,None,69999994,Bảo hiểm nhân thọ Phú Hưng,Female,...,None,,0,2014-08-12,20240126,2014-08-12,Direct Sales,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82843,BMT,Võ Tất Thắng,AD088,,None,60013383,DM - DUMMY 13383,60013527,ĐIỂU KHƯƠI,Male,...,60013383,,1,2018-04-10,20240126,2018-04-10,Buon Ma Thuot,NULL,Võ Tất Thắng,TD
82844,BMT,Võ Tất Thắng,AD088,,None,60019183,FC - LÊ THỊ NGỌC HƯƠNG,60019184,TRẦN THỊ BÍCH PHƯỢNG,Female,...,None,,1,2019-01-16,20240126,2019-01-16,Buon Ma Thuot,NULL,Võ Tất Thắng,TD
82845,BMT,Võ Tất Thắng,AD088,60006494,DM - ĐINH THỊ NGUYÊN,60010702,FC - CAO THỊ CÚC,60012465,NGUYỄN THỊ HƯỜNG,Female,...,60006494,,2,2018-01-16,20240126,2018-01-16,Buon Ma Thuot,NULL,Võ Tất Thắng,TD
82846,LAK,Võ Tất Thắng,AD088,None,None,,None,60044824,DUMMY 44824,Male,...,None,,0,2021-05-31,20240126,2021-05-31,Lak,NULL,Võ Tất Thắng,TD
82847,NTR,Võ Tất Thắng,AD088,None,None,,None,60004431,ĐỒNG THỊ MINH TÂN,Female,...,None,,0,2016-06-30,20240126,2016-06-30,Nha Trang,NULL,Võ Tất Thắng,TD

<h5>1.2 Lấy bảng Commision

In [3]:
com_query = f"""\n
SELECT * FROM [DPO].[DP_TAGENTCOMM_TEST_CUTOFF]
WHERE CUTOFF = {cutoff}
"""
com_table = pd.read_sql(com_query, conn)
com_table

,Policy No,Product Code,Premium transaction,Premium transaction name,Premium Collected,Collected Date,Applied Premium Date,FYC,RYC,Shared Commission Rate,...,Servicing Agent,Commission Agent,Transfer Date,Proposal Receive Date,Freelook,RISK_COMMENCE_DATE,Receive Policy date,Premium Year,CUTOFF,RETURN_DATE
0,80004891,URH1,T642,Contract Issue,147000.0,2016-08-24,2016-08-24,53000.0,0.0,100.0,...,60003445,60003445,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None
1,80004891,UL01,T642,Contract Issue,2500000.0,2016-08-24,2016-08-24,900000.0,0.0,100.0,...,60003445,60003445,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None
2,80004891,URA1,B522,Premium Collection,90000.0,2016-11-25,2016-11-25,33000.0,0.0,100.0,...,60003445,60003445,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None
3,80004891,URH1,B522,Premium Collection,147000.0,2016-11-25,2016-11-25,53000.0,0.0,100.0,...,60003445,60003445,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None
4,80004891,UL01,B522,Premium Collection,2500000.0,2016-11-25,2016-11-25,900000.0,0.0,100.0,...,60003445,60003445,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589562,80148564,RHB1,T642,Contract Issue,1200000.0,2023-06-19,2023-06-19,180000.0,0.0,100.0,...,60079337,60079337,2023-06-19,2023-06-16,215.0,2023-06-16,2023-06-26,1,20240126,None
1589563,80148564,URC5,T642,Contract Issue,720000.0,2023-06-19,2023-06-19,252000.0,0.0,100.0,...,60079337,60079337,2023-06-19,2023-06-16,215.0,2023-06-16,2023-06-26,1,20240126,None
1589564,80148564,URA5,T642,Contract Issue,358000.0,2023-06-19,2023-06-19,125000.0,0.0,100.0,...,60079337,60079337,2023-06-19,2023-06-16,215.0,2023-06-16,2023-06-26,1,20240126,None
1589565,80148565,UL05,T642,Contract Issue,34784000.0,2023-06-19,2023-06-19,13218000.0,0.0,100.0,...,60066942,60066942,2023-06-19,2023-06-17,219.0,2023-06-17,2023-06-22,1,20240126,None
1589566,80148565,URC5,T642,Contract Issue,1110000.0,2023-06-19,2023-06-19,389000.0,0.0,100.0,...,60066942,60066942,2023-06-19,2023-06-17,219.0,2023-06-17,2023-06-22,1,20240126,None

<h3>2. Xây cấu trúc bảng

<h5>2.1 Lấy ra quan hệ giữa người giới thiệu và được giới thiệu

In [5]:
introduce_agent = agent_table
introduce_agent = introduce_agent[['Agent Numer of Introducer', 'Agent_Number']]
introduce_agent = introduce_agent.dropna()
introduce_agent = introduce_agent.rename(columns={'Agent Numer of Introducer':"Introducer", 'Agent_Number': "Introducee"})
introduce_agent

      Introducer Introducee
22      60067197   60067204
23      60055768   60055870
26      60055520   60055768
27      60054844   60055877
28      60059491   60059495
...          ...        ...
82727   60046470   60054817
82728   60055808   60056474
82729   60048350   60049028
82730   60056633   60056637
82838   60024909   60025110

[59893 rows x 2 columns]

<h5>2.2 Móc lấy thông tin cụ thể của người giới thiệu:

In [6]:
introduce_info = pd.merge(introduce_agent, agent_table, left_on = 'Introducer', right_on ='Agent_Number', how='left')
introduce_info = introduce_info[['Introducer', 'Agent_Name', 'Grade', 'Agent_Status', 'Date_Appointed', 'Introducee']].\
rename(columns={'Agent_Name':'IntroducerName', 'Grade': 'IntroducerGrade', 'Agent_Status':'IntroducerStatus', 'Date_Appointed':'IntroducerAppointed'})
introduce_info = introduce_info[introduce_info['IntroducerStatus'] != 'Terminated']
introduce_info

,Introducer,IntroducerName,IntroducerGrade,IntroducerStatus,IntroducerAppointed,Introducee
1,60055768,NGUYỄN THỊ HOA,FC,Inforce,2022-01-19,60055870
3,60054844,PHẠM THỊ LIỆU,FC,Inforce,2021-12-24,60055877
5,60054726,PHẠM THỊ MINH,FC,Inforce,2021-12-23,60056224
7,60061965,TÒNG VĂN THỨC,FC,Inforce,2022-06-23,60063029
9,60057636,LÊ THỊ VIỆN,FC,Inforce,2022-03-28,60058941
...,...,...,...,...,...,...
59886,60043526,LÊ THỊ HẠNH,FC,Inforce,2021-06-07,60043582
59888,60046470,NGUYỄN VĂN TRUNG,FC,Inforce,2021-07-17,60054817
59889,60055808,LÊ VĂN MƯỜI,FC,Inforce,2023-02-20,60056474
59890,60048350,TRIỆU THỊ HƯỜNG,FC,Inforce,2021-08-18,60049028
59891,60056633,NGUYỄN THỊ THẮNG,FC,Inforce,2022-02-23,60056637

<h5>2.3 Móc lấy thông tin cụ thể người được giới thiệu:

In [7]:
introducee_info = pd.merge(introduce_info, agent_table, left_on = 'Introducee', right_on ='Agent_Number', how ='left')
introducee_info = introducee_info[['Introducer', 'IntroducerName', 'IntroducerGrade', 'IntroducerStatus','IntroducerAppointed', 
        'Introducee', 'Agent_Name', 'Grade', 'Agent_Status', 'Date_Appointed', 'Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'CUTOFF']].\
rename(columns={'Agent_Name':'IntroduceeName', 'Grade': 'IntroduceeGrade', 'Agent_Status':'IntroduceeStatus', 'Date_Appointed':'IntroduceeAppointed',
               'Sales_Unit':"AD_Name", 'Sales_Unit_Code':'AD_Code'})
introducee_info['Appointed_Temp'] = np.where(introducee_info['IntroduceeAppointed'].dt.day > 10, 
        introducee_info['IntroduceeAppointed'] + pd.DateOffset(months=1), introducee_info['IntroduceeAppointed'])
introducee_info['Appointed_Temp'] = introducee_info['Appointed_Temp'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
introducee_info['Date_On_Set'] = pd.to_datetime(introducee_info['CUTOFF'].str[:4]+"-"+introducee_info['CUTOFF'].str[4:6]+"-"+introducee_info['CUTOFF'].str[6:])
introducee_info['Date_Temp'] = introducee_info['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
introducee_info['Length of Service(Months)'] = (introducee_info['Date_Temp'].dt.to_period('M').astype('int64') +1 ) - introducee_info['Appointed_Temp'].dt.to_period('M').astype('int64')
introducee_info = introducee_info.loc[:, ~introducee_info.columns.isin(['Date_On_Set', 'Date_Temp', 'Appointed_Temp'])]
introducee_info = introducee_info[introducee_info['IntroduceeStatus'] != 'Terminated']
introducee_info

,Introducer,IntroducerName,IntroducerGrade,IntroducerStatus,IntroducerAppointed,Introducee,IntroduceeName,IntroduceeGrade,IntroduceeStatus,IntroduceeAppointed,Area_Name,AD_Code,AD_Name,CUTOFF,Length of Service(Months)
0,60055768,NGUYỄN THỊ HOA,FC,Inforce,2022-01-19,60055870,VÕ THỊ YÊN,FC,Inforce,2022-01-21,ADG,A1042,Đỗ Anh Tuấn,20240126,24
1,60054844,PHẠM THỊ LIỆU,FC,Inforce,2021-12-24,60055877,PHẠM THỊ HƯƠNG,FC,Inforce,2022-01-21,ADG,A1042,Đỗ Anh Tuấn,20240126,24
2,60054726,PHẠM THỊ MINH,FC,Inforce,2021-12-23,60056224,NGUYỄN THỊ PHẨM,FC,Inforce,2022-02-16,ADG,A1042,Đỗ Anh Tuấn,20240126,23
4,60057636,LÊ THỊ VIỆN,FC,Inforce,2022-03-28,60058941,THÀO A MANH,FC,Inforce,2022-04-29,ALC,A1042,Đỗ Anh Tuấn,20240126,21
8,60057635,NGUYỄN THỊ HƯỜNG,FM,Inforce,2022-07-25,60067434,TRẦN THỊ THỦY,FC,Inforce,2022-08-13,ALC,A1042,Đỗ Anh Tuấn,20240126,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31387,60043526,LÊ THỊ HẠNH,FC,Inforce,2021-06-07,60043582,THÁI HỮU DUẨN,FC,Inforce,2021-06-07,SHI,AD212,Lê Thị Thùy Dung,20240126,32
31388,60046470,NGUYỄN VĂN TRUNG,FC,Inforce,2021-07-17,60054817,LÊ THỊ THỤY,FC,Inforce,2021-12-23,SHI,AD212,Lê Thị Thùy Dung,20240126,25
31389,60055808,LÊ VĂN MƯỜI,FC,Inforce,2023-02-20,60056474,LA Ô Y THANH,FC,Inforce,2022-02-23,SHI,AD212,Lê Thị Thùy Dung,20240126,23
31390,60048350,TRIỆU THỊ HƯỜNG,FC,Inforce,2021-08-18,60049028,ĐẶNG THỊ HOA,FC,Inforce,2021-08-25,SHI,AD212,Lê Thị Thùy Dung,20240126,29
31391,60056633,NGUYỄN THỊ THẮNG,FC,Inforce,2022-02-23,60056637,VÕ KHẮC LIÊN TÂM,FC,Inforce,2022-02-23,SHI,AD212,Lê Thị Thùy Dung,20240126,23

<h3>3. Tính hoa hồng

<h5>3.1 Lấy ra ngày đầu tiên (thay đổi theo các ngày CUTOFF):

In [8]:
com_t = com_table
com_t['Date_On_Set'] = pd.to_datetime(com_t['CUTOFF'].str[:4]+"-"+com_t['CUTOFF'].str[4:6]+"-"+com_t['CUTOFF'].str[6:])
if ('20230531' in com_t['CUTOFF'].values):
    com_t.loc[:,'Start_Month'] = '2023-04-30'
elif ('20220228' in com_t['CUTOFF'].values):
    com_t.loc[:,'Start_Month'] = '2022-01-28'
elif ('20220429' in com_t['CUTOFF'].values):
    com_t.loc[:,'Start_Month'] = '2022-03-31'
elif ('20220531' in com_t['CUTOFF'].values):
    com_t.loc[:,'Start_Month'] = '2022-04-30' 
elif ('20240229' in com_t['CUTOFF'].values):
    com_t.loc[:,'Start_Month'] = '2024-01-27'
else: 
    com_t['Start_Month'] = (com_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1))
com_t
#Lấy kỳ xét và loại ra các trạng thái HD hủy, chưa pass 21 ngày FL
com_t = com_t[(com_t['Freelook'] >21)]
com_t = com_t[~com_t['Policy Status'].isin(['CF', 'DC', 'FL', 'NT', 'WD', 'PO', 'SU', 'TR'])]
com_t

,Policy No,Product Code,Premium transaction,Premium transaction name,Premium Collected,Collected Date,Applied Premium Date,FYC,RYC,Shared Commission Rate,...,Transfer Date,Proposal Receive Date,Freelook,RISK_COMMENCE_DATE,Receive Policy date,Premium Year,CUTOFF,RETURN_DATE,Date_On_Set,Start_Month
0,80004891,URH1,T642,Contract Issue,147000.0,2016-08-24,2016-08-24,53000.0,0.0,100.0,...,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None,2024-01-26,2024-01-01
1,80004891,UL01,T642,Contract Issue,2500000.0,2016-08-24,2016-08-24,900000.0,0.0,100.0,...,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None,2024-01-26,2024-01-01
2,80004891,URA1,B522,Premium Collection,90000.0,2016-11-25,2016-11-25,33000.0,0.0,100.0,...,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None,2024-01-26,2024-01-01
3,80004891,URH1,B522,Premium Collection,147000.0,2016-11-25,2016-11-25,53000.0,0.0,100.0,...,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None,2024-01-26,2024-01-01
4,80004891,UL01,B522,Premium Collection,2500000.0,2016-11-25,2016-11-25,900000.0,0.0,100.0,...,2016-08-24,2016-08-23,2707.0,2016-08-23,2016-08-29,1,20240126,None,2024-01-26,2024-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589562,80148564,RHB1,T642,Contract Issue,1200000.0,2023-06-19,2023-06-19,180000.0,0.0,100.0,...,2023-06-19,2023-06-16,215.0,2023-06-16,2023-06-26,1,20240126,None,2024-01-26,2024-01-01
1589563,80148564,URC5,T642,Contract Issue,720000.0,2023-06-19,2023-06-19,252000.0,0.0,100.0,...,2023-06-19,2023-06-16,215.0,2023-06-16,2023-06-26,1,20240126,None,2024-01-26,2024-01-01
1589564,80148564,URA5,T642,Contract Issue,358000.0,2023-06-19,2023-06-19,125000.0,0.0,100.0,...,2023-06-19,2023-06-16,215.0,2023-06-16,2023-06-26,1,20240126,None,2024-01-26,2024-01-01
1589565,80148565,UL05,T642,Contract Issue,34784000.0,2023-06-19,2023-06-19,13218000.0,0.0,100.0,...,2023-06-19,2023-06-17,219.0,2023-06-17,2023-06-22,1,20240126,None,2024-01-26,2024-01-01
1589566,80148565,URC5,T642,Contract Issue,1110000.0,2023-06-19,2023-06-19,389000.0,0.0,100.0,...,2023-06-19,2023-06-17,219.0,2023-06-17,2023-06-22,1,20240126,None,2024-01-26,2024-01-01

<h5>3.2 Tính hoa hồng theo hợp đồng

In [9]:
#Cộng thêm 21 ngày ACK để có kỳ xét hoa hồng chính thức
cal_com = com_t
cal_com['Valid_Date'] = np.where(cal_com['Receive Policy date'] >= cal_com['Applied Premium Date'], cal_com['Receive Policy date'], cal_com['Applied Premium Date'])
cal_com['Valid_Date'] = cal_com['Valid_Date'] + timedelta(days=22) #+22 để bảo đảm qua được 21 ngày cân nhắc
cal_com = cal_com[(cal_com['Valid_Date'] >= cal_com['Start_Month']) & (cal_com['Valid_Date'] <= cal_com['Date_On_Set'])
        & cal_com['FYC'] != 0]
cal_com = cal_com.groupby(['Commission Agent','Policy No', 'Issued Date', 'Applied Premium Date', 'Receive Policy date', 'Freelook'], dropna=False)[['FYC', 'Premium Collected']].sum().reset_index()
cal_com

,Commission Agent,Policy No,Issued Date,Applied Premium Date,Receive Policy date,Freelook,FYC,Premium Collected
0,60006926,80011534,2017-04-27,2023-12-25,2017-05-04,2459.0,7000.0,715000.0
1,60008955,80007343,2016-11-28,2023-12-19,2016-12-06,2608.0,271000.0,712000.0
2,60012256,80029648,2018-09-20,2023-12-22,2018-09-25,1950.0,581000.0,1529000.0
3,60014874,80130680,2022-12-30,2023-12-29,2023-01-13,379.0,2000.0,178000.0
4,60018133,80088288,2021-08-04,2023-12-11,2021-08-14,896.0,284000.0,1036000.0
...,...,...,...,...,...,...,...,...
95,60082878,80156507,2023-11-30,2023-11-30,2023-12-16,42.0,1352000.0,4507000.0
96,60083065,80154767,2023-07-31,2023-07-31,2023-12-25,33.0,2610000.0,7055000.0
97,60083451,80156505,2023-11-30,2023-11-30,2023-12-11,47.0,1318000.0,4706000.0
98,60083471,80156497,2023-11-30,2023-11-30,2023-12-14,44.0,4545000.0,14001000.0
99,60083471,80156517,2023-12-15,2023-12-15,2023-12-23,35.0,4765000.0,14000000.0

<h3> 4. Ghép lại thông tin

In [10]:
agent_com = pd.merge(introducee_info, cal_com, left_on = 'Introducee', right_on ='Commission Agent', how ='left')
agent_com = agent_com[agent_com['Commission Agent'].notnull()]
agent_com

,Introducer,IntroducerName,IntroducerGrade,IntroducerStatus,IntroducerAppointed,Introducee,IntroduceeName,IntroduceeGrade,IntroduceeStatus,IntroduceeAppointed,...,CUTOFF,Length of Service(Months),Commission Agent,Policy No,Issued Date,Applied Premium Date,Receive Policy date,Freelook,FYC,Premium Collected
867,60019288,HỒ THỊ THANH HƯƠNG,FC,Inforce,2019-01-21,60020041,MẠCH TÚ KHANH,FC,Inforce,2019-03-05,...,20240126,59,60020041,80054117,2019-12-19,2023-12-18,2019-12-24,1495.0,74000.0,1841000.0
1125,60073118,MAI VĂN HOÀI,FM,Inforce,2022-11-22,60072329,HỒ THỊ GIANG,FC,Inforce,2022-11-23,...,20240126,14,60072329,80129997,2022-12-27,2023-12-20,2023-01-03,389.0,4000.0,387000.0
1378,60080461,NGUYỄN VĂN NGHĨA,FM,Inforce,2023-05-26,60080462,PHAN THỦY BÍCH,FC,Inforce,2023-05-26,...,20240126,8,60080462,80156522,2023-12-28,2023-12-28,2024-01-04,23.0,1940000.0,4850000.0
1456,60080977,ĐỖ VĂN MINH,DM,Inforce,2023-06-05,60083451,NGUYỄN THỊ THÚY,DM,Inforce,2023-08-28,...,20240126,5,60083451,80156505,2023-11-30,2023-11-30,2023-12-11,47.0,1318000.0,4706000.0
1503,60082756,BÙI DIỆP ANH,DM,Inforce,2023-08-02,60082206,NGUYỄN VÂN ANH,DM,Inforce,2023-08-02,...,20240126,6,60082206,80156527,2023-12-28,2023-12-28,2024-01-03,24.0,1547000.0,4606000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13877,60079742,NGUYỄN THỊ MAI,DM,Inforce,2023-06-24,60077255,TRƯƠNG NGỌC LINH ĐAN,FC,Inforce,2023-05-13,...,20240126,8,60077255,80145918,2023-05-29,2023-12-28,2023-06-02,239.0,1849000.0,5058000.0
14320,60044385,PHÙNG THỊ SĨ,FC,Inforce,2021-06-05,60047132,LÊ KỶ NIỆM,FC,Inforce,2021-07-28,...,20240126,30,60047132,80100800,2021-12-31,2023-12-28,2022-01-17,740.0,185000.0,2303000.0
14874,60076580,BÙI THỊ THẢO,DM,Inforce,2023-02-22,60076523,NGUYỄN THỊ THU HOÀI,FC,Inforce,2023-02-23,...,20240126,11,60076523,80143192,2023-05-08,2023-05-08,2023-12-23,35.0,6800000.0,17000000.0
14875,60076580,BÙI THỊ THẢO,DM,Inforce,2023-02-22,60076523,NGUYỄN THỊ THU HOÀI,FC,Inforce,2023-02-23,...,20240126,11,60076523,80143193,2023-05-08,2023-05-08,2023-12-23,35.0,5200000.0,13000000.0
14913,60080379,NGÔ THỊ THẮM,DM,Inforce,2023-05-22,60080313,NGUYỄN THỊ THU HÒA,FM,Inforce,2023-07-17,...,20240126,6,60080313,80156427,2023-10-31,2023-10-31,2023-12-24,34.0,1098000.0,8631000.0

In [11]:
agent_com.to_csv('checkcom.csv', encoding = 'utf-8-sig')