In [1]:
import numpy as np
import pandas as pd
import pyodbc as pyo
import sqlalchemy as sa
import numpy as np
import math
import datetime
import datetime as dt
#Kết nối SV_UAT (SQL_SV64)
connection_uri_UAT = (
    "mssql+pyodbc://PHLHCMHOPPBI02\PBIRS/PowerBI?driver=ODBC+Driver+17+for+SQL+Server"
)
conn = sa.create_engine(connection_uri_UAT)

<h3>1. Lấy bảng

In [2]:
cutoff = input("Nhập kỳ CUTOFF cuối tháng YYYYMMDD: ")

Nhập kỳ CUTOFF cuối tháng YYYYMMDD: 20230331

<h5>1.1 Lấy bảng AgentInfo

In [3]:
agent_query = f"""\n
SELECT * FROM [DPO].[Main_AGENT_INFO_DA_CUTOFF]
WHERE CUTOFF = {cutoff}
"""
agent_table = pd.read_sql(agent_query, conn)
agent_table

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,Leader,SFC,Leader_count,Appointed_TAPSU,CUTOFF,First_Appointed,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade
0,ABL,Trần Hữu Nghị,AD329,None,None,,None,60032190,NGUYỄN VŨ THANH,Male,...,None,,0,2020-10-28,20230331,2020-10-28,None,None,None,None
1,ABL,Trần Hữu Nghị,AD329,None,None,,None,60034088,LÊ VŨ LUÂN,Male,...,None,,0,2020-12-19,20230331,2020-12-19,None,None,None,None
2,ABL,Trần Hữu Nghị,AD329,None,None,,None,60034820,HUỲNH NHẬT DƯƠNG,Female,...,None,,0,2020-12-24,20230331,2020-12-24,None,None,None,None
3,ABL,Trần Hữu Nghị,AD329,None,None,,None,60034821,NGUYỄN THỊ TIỂU BĂNG,Female,...,None,,0,2020-12-24,20230331,2020-12-24,None,None,None,None
4,ABL,Trần Hữu Nghị,AD329,,None,60028178,FM - TRẦN MÃNH KHƯƠNG,60028188,NGUYỄN VĂN ĐẠT,Male,...,60028178,,1,2020-08-19,20230331,2020-08-19,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77883,ABL,Trần Hữu Nghị,AD329,,None,60028656,FM - NGUYỄN TÚ ÚT,60045838,VƯƠNG THẾ HUY,Female,...,60028656,,1,2021-06-28,20230331,2021-06-28,None,None,None,None
77884,ABL,Trần Hữu Nghị,AD329,,None,60028656,FM - NGUYỄN TÚ ÚT,60048390,PHẠM THANH SANG,Male,...,None,,1,2021-08-19,20230331,2021-08-19,None,None,None,None
77885,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60071016,NGUYỄN NHƯ TIỆP,Female,...,60028179,,1,2022-10-19,20230331,2022-10-19,None,None,None,None
77886,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60071018,HUỲNH HOÀNG DUY,Male,...,60028179,,1,2022-10-19,20230331,2022-11-21,None,None,None,None
77887,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60072139,TRẦN QUỐC THÁI,Male,...,60028179,,1,2022-12-31,20230331,2022-12-31,None,None,None,None

<h5>1.2 Lấy bảng PREMIUM

In [9]:
premium_query = f"""\n
SELECT * FROM [DPO].[DP_TAGENTPREMIUM_TEST_CUTOFF]
WHERE CUTOFF = {cutoff}
"""
premium_table = pd.read_sql(premium_query, conn)
premium_table

,Policy No,Product Code,Premium transaction,PREM TRAN NAME,Premium Collected,Collected Date,Applied Premium Date,FYP Before Discount,FYP Discount,FYP,...,Area Code,Servicing Agent,Freelook,Proposal Receive Date,RISK_COMMENCE_DATE,Age_Customer,Issuing Agent,AFYP,CUTOFF,RETURN_DATE
0,80000951,EN03,B522,Premium Collection,2525000.0,2018-05-07,2018-05-07,0.0,0.0,0.0,...,SG1,60000321,2704.0,2015-10-31,2015-10-30,52.0,60000286,9.890566e+06,20230331,None
1,80000951,RAC2,B522,Premium Collection,146000.0,2018-07-31,2018-07-31,0.0,0.0,0.0,...,SG1,60000321,2704.0,2015-10-31,2015-10-30,52.0,60000286,9.890566e+06,20230331,None
2,80000951,EN03,B522,Premium Collection,2525000.0,2018-07-31,2018-07-31,0.0,0.0,0.0,...,SG1,60000321,2704.0,2015-10-31,2015-10-30,52.0,60000286,9.890566e+06,20230331,None
3,80000951,RAC2,B522,Premium Collection,146000.0,2018-10-30,2018-10-30,0.0,0.0,0.0,...,SG1,60000321,2704.0,2015-10-31,2015-10-30,52.0,60000286,9.890566e+06,20230331,None
4,80000951,EN03,B522,Premium Collection,2525000.0,2018-10-30,2018-10-30,0.0,0.0,0.0,...,SG1,60000321,2704.0,2015-10-31,2015-10-30,52.0,60000286,9.890566e+06,20230331,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1351454,80005129,RTR1,T642,Contract Issue,242000.0,2016-08-30,2016-08-30,242000.0,0.0,242000.0,...,DTH,60003420,2398.0,2016-08-29,2016-08-29,24.0,60003420,9.665000e+06,20230331,None
1351455,80005129,RCI1,T642,Contract Issue,523000.0,2016-08-30,2016-08-30,523000.0,0.0,523000.0,...,DTH,60003420,2398.0,2016-08-29,2016-08-29,24.0,60003420,9.665000e+06,20230331,None
1351456,80005129,RAC2,T642,Contract Issue,360000.0,2016-08-30,2016-08-30,360000.0,0.0,360000.0,...,DTH,60003420,2398.0,2016-08-29,2016-08-29,25.0,60003420,9.665000e+06,20230331,None
1351457,80005129,RHB1,T642,Contract Issue,480000.0,2016-08-30,2016-08-30,480000.0,0.0,480000.0,...,DTH,60003420,2398.0,2016-08-29,2016-08-29,24.0,60003420,9.665000e+06,20230331,None
1351458,80005129,RAC2,B522,Premium Collection,360000.0,2017-08-29,2017-08-29,0.0,0.0,0.0,...,DTH,60003420,2398.0,2016-08-29,2016-08-29,25.0,60003420,9.665000e+06,20230331,None

<h3>2. Lấy ra ngày xét

In [11]:
agent_t = agent_table

In [18]:
agent_t['Date_On_Set'] = pd.to_datetime(agent_t['CUTOFF'].str[:4]+"-"+agent_t['CUTOFF'].str[4:6]+"-"+agent_t['CUTOFF'].str[6:])
#Lấy ngày xét tạm:
#Rule: Join sau ngày 10 hàng tháng, tính sang tháng sau:
agent_t['Date_1st_Temp'] = np.where(agent_t['Date_Appointed'].dt.day > 10, 
        agent_t['Date_Appointed'] + pd.DateOffset(months=1), agent_t['Date_Appointed'])
agent_t['Date_1st_Temp'] = agent_t['Date_1st_Temp'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
agent_t['1st_month'] = agent_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1) - pd.DateOffset(months=2)
agent_t['2nd_month'] = agent_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1) - pd.DateOffset(months=1)
agent_t['3rd_month'] = agent_t['Date_On_Set'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
agent_t

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,First_Appointed,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month
0,ABL,Trần Hữu Nghị,AD329,None,None,,None,60032190,NGUYỄN VŨ THANH,Male,...,2020-10-28,None,None,None,None,2023-03-31,2020-11-01,2023-01-01,2023-02-01,2023-03-01
1,ABL,Trần Hữu Nghị,AD329,None,None,,None,60034088,LÊ VŨ LUÂN,Male,...,2020-12-19,None,None,None,None,2023-03-31,2021-01-01,2023-01-01,2023-02-01,2023-03-01
2,ABL,Trần Hữu Nghị,AD329,None,None,,None,60034820,HUỲNH NHẬT DƯƠNG,Female,...,2020-12-24,None,None,None,None,2023-03-31,2021-01-01,2023-01-01,2023-02-01,2023-03-01
3,ABL,Trần Hữu Nghị,AD329,None,None,,None,60034821,NGUYỄN THỊ TIỂU BĂNG,Female,...,2020-12-24,None,None,None,None,2023-03-31,2021-01-01,2023-01-01,2023-02-01,2023-03-01
4,ABL,Trần Hữu Nghị,AD329,,None,60028178,FM - TRẦN MÃNH KHƯƠNG,60028188,NGUYỄN VĂN ĐẠT,Male,...,2020-08-19,None,None,None,None,2023-03-31,2020-09-01,2023-01-01,2023-02-01,2023-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77883,ABL,Trần Hữu Nghị,AD329,,None,60028656,FM - NGUYỄN TÚ ÚT,60045838,VƯƠNG THẾ HUY,Female,...,2021-06-28,None,None,None,None,2023-03-31,2021-07-01,2023-01-01,2023-02-01,2023-03-01
77884,ABL,Trần Hữu Nghị,AD329,,None,60028656,FM - NGUYỄN TÚ ÚT,60048390,PHẠM THANH SANG,Male,...,2021-08-19,None,None,None,None,2023-03-31,2021-09-01,2023-01-01,2023-02-01,2023-03-01
77885,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60071016,NGUYỄN NHƯ TIỆP,Female,...,2022-10-19,None,None,None,None,2023-03-31,2022-11-01,2023-01-01,2023-02-01,2023-03-01
77886,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60071018,HUỲNH HOÀNG DUY,Male,...,2022-11-21,None,None,None,None,2023-03-31,2022-12-01,2023-01-01,2023-02-01,2023-03-01
77887,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60072139,TRẦN QUỐC THÁI,Male,...,2022-12-31,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01

<h5>2.1 Lấy ra ngày cần xét trong 3 tháng gia nhập gần nhất

In [19]:
agent_rookie = agent_t[(agent_t['Date_1st_Temp'] >= agent_t['1st_month']) & (agent_t['Date_1st_Temp'] <= agent_t['Date_On_Set'])]
agent_rookie['Rookie_Month'] = np.where(agent_rookie['Date_1st_Temp'] == agent_rookie['3rd_month'], "1",
                            np.where(agent_rookie['Date_1st_Temp'] == agent_rookie['2nd_month'], "2",
                            "3"))
agent_rookie

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\1443559686.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_rookie['Rookie_Month'] = np.where(agent_rookie['Date_1st_Temp'] == agent_rookie['3rd_month'], "1",

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,Area_Desc,TERRITORY,HOT Name,Sale_Unit_Grade,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month
93,AHL,Nguyễn Thị Hồng,AD642,60074823,FM - PHẠM THỊ NGÂN,60074824,FM - NGUYỄN THỊ TÂM,60074670,TRẦN THỊ HOÀI ANH,Female,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
94,AHN,AG Bùi Thị Bích Ngọc,AD840,,None,60073409,DM - BÙI XUÂN HÀ,60075282,HOÀNG THỊ HOA,Female,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
95,AHN,AG Bùi Thị Bích Ngọc,AD840,,None,60073409,DM - BÙI XUÂN HÀ,60075362,ĐỖ HUY THẮNG,Male,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
107,ACM,Phạm Phương Liên,AD457,60041521,DM - NGUYỄN THỊ ÁNH XUÂN,60033846,DM - DƯƠNG MỸ HIÊN,60075425,NGUYỄN VĂN HÓA,Male,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
127,AHP,AG Lê Minh Tuấn,AD747,60067248,FM - TRẦN THỊ HỒNG GIANG,60073050,FM - ĐỖ CẢNH TOÀN,60074460,ĐỖ MẠNH THẮNG,Male,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77613,YTH,Hoàng Thị Luân,AD966,60073079,DM - TRẦN THỊ GIANG,60074519,DM - DUMMY VI THỊ PHƯỢNG,60074521,DUMMY LÔ THỊ QUÀNH,Female,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
77614,YTH,Hoàng Thị Luân,AD966,60073079,DM - TRẦN THỊ GIANG,60074519,DM - DUMMY VI THỊ PHƯỢNG,60074523,DUMMY VI THỊ NGA,Female,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3
77615,YTH,Hoàng Thị Luân,AD966,60074114,DM - DUMMY PHAN THỊ THANH NGẦN,60077124,DM - DUMMY HÀ THỊ SOA,60077034,ĐINH VIẾT LONG,Male,...,None,None,None,None,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1
77687,YTH,Ngô Thị Liên,A1057,None,None,,None,60077150,DUMMY NGUYỄN THỊ YẾN,Female,...,None,None,None,None,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1
77887,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60072139,TRẦN QUỐC THÁI,Male,...,None,None,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3

<h5>2.2 Set Target FYP và CC:

In [42]:
agent_target = agent_rookie
agent_target['FYP Target'] = np.where(agent_target['Rookie_Month'] == '3', 72000000,
                       np.where(agent_target['Rookie_Month'] == '2', 48000000,
                      np.where(agent_target['Rookie_Month'] == '1', 24000000, 0)))
agent_target['CC Target'] = np.where(agent_target['Rookie_Month'] == '3', 6,
                       np.where(agent_target['Rookie_Month'] == '2', 4,
                      np.where(agent_target['Rookie_Month'] == '1', 2, 0)))
agent_target

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\4197385297.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_target['FYP Target'] = np.where(agent_target['Rookie_Month'] == '3', 72000000,
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\4197385297.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agent_target['CC Target'] = np.where(agent_target['Rookie_Month'] == '3', 6,

,Area_Name,Sales_Unit,Sales_Unit_Code,Parent_Supervisor_Code,Parent_Supervisor_Name,Supervisor_Code,Supervisor_Name,Agent_Number,Agent_Name,Gender,...,HOT Name,Sale_Unit_Grade,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month,FYP Target,CC Target
93,AHL,Nguyễn Thị Hồng,AD642,60074823,FM - PHẠM THỊ NGÂN,60074824,FM - NGUYỄN THỊ TÂM,60074670,TRẦN THỊ HOÀI ANH,Female,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
94,AHN,AG Bùi Thị Bích Ngọc,AD840,,None,60073409,DM - BÙI XUÂN HÀ,60075282,HOÀNG THỊ HOA,Female,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
95,AHN,AG Bùi Thị Bích Ngọc,AD840,,None,60073409,DM - BÙI XUÂN HÀ,60075362,ĐỖ HUY THẮNG,Male,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
107,ACM,Phạm Phương Liên,AD457,60041521,DM - NGUYỄN THỊ ÁNH XUÂN,60033846,DM - DƯƠNG MỸ HIÊN,60075425,NGUYỄN VĂN HÓA,Male,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
127,AHP,AG Lê Minh Tuấn,AD747,60067248,FM - TRẦN THỊ HỒNG GIANG,60073050,FM - ĐỖ CẢNH TOÀN,60074460,ĐỖ MẠNH THẮNG,Male,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77613,YTH,Hoàng Thị Luân,AD966,60073079,DM - TRẦN THỊ GIANG,60074519,DM - DUMMY VI THỊ PHƯỢNG,60074521,DUMMY LÔ THỊ QUÀNH,Female,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
77614,YTH,Hoàng Thị Luân,AD966,60073079,DM - TRẦN THỊ GIANG,60074519,DM - DUMMY VI THỊ PHƯỢNG,60074523,DUMMY VI THỊ NGA,Female,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
77615,YTH,Hoàng Thị Luân,AD966,60074114,DM - DUMMY PHAN THỊ THANH NGẦN,60077124,DM - DUMMY HÀ THỊ SOA,60077034,ĐINH VIẾT LONG,Male,...,None,None,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000,2
77687,YTH,Ngô Thị Liên,A1057,None,None,,None,60077150,DUMMY NGUYỄN THỊ YẾN,Female,...,None,None,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000,2
77887,ABL,Trần Hữu Nghị,AD329,,None,60028179,DM - NGUYỄN THỊ HUYỀN CHÂN,60072139,TRẦN QUỐC THÁI,Male,...,None,None,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6

In [43]:
agent_target = agent_target[['Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'Agent_Number', 'Agent_Name', 'Grade', 
         'Agent_Status', 'Date_Appointed', 'CUTOFF', 'Date_On_Set', 'Date_1st_Temp', 
        '1st_month', '2nd_month', '3rd_month', 'Rookie_Month','FYP Target', 'CC Target']]
agent_target

,Area_Name,Sales_Unit_Code,Sales_Unit,Agent_Number,Agent_Name,Grade,Agent_Status,Date_Appointed,CUTOFF,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month,FYP Target,CC Target
93,AHL,AD642,Nguyễn Thị Hồng,60074670,TRẦN THỊ HOÀI ANH,FC,Enforce,2022-12-26,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
94,AHN,AD840,AG Bùi Thị Bích Ngọc,60075282,HOÀNG THỊ HOA,FC,Enforce,2022-12-23,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
95,AHN,AD840,AG Bùi Thị Bích Ngọc,60075362,ĐỖ HUY THẮNG,FM,Enforce,2022-12-24,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
107,ACM,AD457,Phạm Phương Liên,60075425,NGUYỄN VĂN HÓA,FC,Enforce,2022-12-28,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
127,AHP,AD747,AG Lê Minh Tuấn,60074460,ĐỖ MẠNH THẮNG,FC,Enforce,2022-12-15,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77613,YTH,AD966,Hoàng Thị Luân,60074521,DUMMY LÔ THỊ QUÀNH,FM,Enforce,2022-12-13,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
77614,YTH,AD966,Hoàng Thị Luân,60074523,DUMMY VI THỊ NGA,FM,Enforce,2022-12-13,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6
77615,YTH,AD966,Hoàng Thị Luân,60077034,ĐINH VIẾT LONG,FM,Enforce,2023-03-07,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000,2
77687,YTH,A1057,Ngô Thị Liên,60077150,DUMMY NGUYỄN THỊ YẾN,DM,Enforce,2023-03-08,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000,2
77887,ABL,AD329,Trần Hữu Nghị,60072139,TRẦN QUỐC THÁI,FC,Enforce,2022-12-31,20230331,2023-03-31,2023-01-01,2023-01-01,2023-02-01,2023-03-01,3,72000000,6

<h3> 3. Tính FYP

In [44]:
fyp_cal = premium_table
fyp_cal = fyp_cal[['Servicing Agent', 'Applied Premium Date', 'POLICY ACKNOWLED', 'Policy Status', 'FYP', 'Topup Premium']]
fyp_cal['FYP_Total'] = fyp_cal['FYP'] + fyp_cal['Topup Premium']*0.1
fyp_cal = fyp_cal.groupby(['Servicing Agent', 'Applied Premium Date', 'POLICY ACKNOWLED', 'Policy Status'])['FYP_Total'].sum().reset_index()
fyp_cal = fyp_cal[~fyp_cal['Policy Status'].isin(['CF', 'DC', 'FL',  'NT', 'WD', 'PO'])]
fyp_cal

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\241598806.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fyp_cal['FYP_Total'] = fyp_cal['FYP'] + fyp_cal['Topup Premium']*0.1

,Servicing Agent,Applied Premium Date,POLICY ACKNOWLED,Policy Status,FYP_Total
0,60000002,2014-07-21,2014-08-13,LA,5088000.0
1,60000002,2015-06-21,2014-08-13,LA,0.0
2,60000003,2014-05-30,2014-06-04,LA,4500000.0
3,60000003,2014-06-16,2014-06-17,LA,2815000.0
4,60000003,2014-06-30,2014-07-07,LA,2518000.0
...,...,...,...,...,...
278168,69999999,2023-01-27,2014-12-12,IF,0.0
278169,69999999,2023-02-02,2014-12-17,IF,0.0
278170,69999999,2023-02-27,2015-03-04,IF,0.0
278171,69999999,2023-02-28,2015-10-05,IF,0.0
278172,69999999,2023-03-25,2015-09-29,IF,0.0

<h5>3.1 Lọc các dòng FYP được tính

In [113]:
fyp_date = pd.merge(fyp_cal, agent_target, left_on = 'Servicing Agent', right_on ='Agent_Number', how = 'left')
fyp_date = fyp_date[(fyp_date['POLICY ACKNOWLED']>=fyp_date['Date_Appointed']) & (fyp_date['POLICY ACKNOWLED']<=fyp_date['Date_On_Set'])]
#Lọc ra các TH đã pass 21 ngày FL:
fyp_date['Check_FL'] = (fyp_date['Date_On_Set'] - fyp_date['POLICY ACKNOWLED'])/pd.offsets.Day(1)
fyp_date = fyp_date[fyp_date['Check_FL'] >=21]
fyp_date

,Servicing Agent,Applied Premium Date,POLICY ACKNOWLED,Policy Status,FYP_Total,Area_Name,Sales_Unit_Code,Sales_Unit,Agent_Number,Agent_Name,...,CUTOFF,Date_On_Set,Date_1st_Temp,1st_month,2nd_month,3rd_month,Rookie_Month,FYP Target,CC Target,Check_FL
22661,60005807,2023-02-02,2023-02-07,IF,25236000.0,DNA,AD800,Lý Đăng Khoa,60005807,NGUYỄN THANH LONG,...,20230331,2023-03-31,2023-02-01,2023-01-01,2023-02-01,2023-03-01,2,48000000.0,4.0,52.0
22662,60005807,2023-02-03,2023-02-07,IF,24782000.0,DNA,AD800,Lý Đăng Khoa,60005807,NGUYỄN THANH LONG,...,20230331,2023-03-31,2023-02-01,2023-01-01,2023-02-01,2023-03-01,2,48000000.0,4.0,52.0
22663,60005807,2023-02-23,2023-02-27,IF,14515000.0,DNA,AD800,Lý Đăng Khoa,60005807,NGUYỄN THANH LONG,...,20230331,2023-03-31,2023-02-01,2023-01-01,2023-02-01,2023-03-01,2,48000000.0,4.0,32.0
22664,60005807,2023-03-08,2023-03-10,IF,41990000.0,DNA,AD800,Lý Đăng Khoa,60005807,NGUYỄN THANH LONG,...,20230331,2023-03-31,2023-02-01,2023-01-01,2023-02-01,2023-03-01,2,48000000.0,4.0,21.0
31300,60007436,2023-02-09,2023-02-13,IF,50030000.0,DNA,AD800,Lý Đăng Khoa,60007436,PHẠM KIỀU NỮ BÍCH QUYÊN,...,20230331,2023-03-31,2023-02-01,2023-01-01,2023-02-01,2023-03-01,2,48000000.0,4.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261382,60077057,2023-03-07,2023-03-09,IF,28222000.0,DNA,AD800,Lý Đăng Khoa,60077057,NGUYỄN THỊ HOÀI TRANG,...,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000.0,2.0,22.0
261383,60077057,2023-03-08,2023-03-10,IF,18179000.0,DNA,AD800,Lý Đăng Khoa,60077057,NGUYỄN THỊ HOÀI TRANG,...,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000.0,2.0,21.0
261391,60077084,2023-03-03,2023-03-09,IF,58323000.0,SG1,AD777,Nguyễn Thị Hồng Loan,60077084,BÙI THỊ THANH HẠNH,...,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000.0,2.0,22.0
261392,60077084,2023-03-06,2023-03-09,IF,21396000.0,SG1,AD777,Nguyễn Thị Hồng Loan,60077084,BÙI THỊ THANH HẠNH,...,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000.0,2.0,22.0
261394,60077099,2023-03-06,2023-03-09,IF,10058000.0,VNI,A1035,Trần Thị Kim Á,60077099,TRẦN THỊ KIM ÂU,...,20230331,2023-03-31,2023-03-01,2023-01-01,2023-02-01,2023-03-01,1,24000000.0,2.0,22.0

<h5>3.2 Tổng lấy FYP 3 tháng

In [114]:
fyp_date = fyp_date[['Servicing Agent', 'Applied Premium Date', 'POLICY ACKNOWLED',
       'Policy Status', 'FYP_Total', 'Date_On_Set', 'Date_1st_Temp', '1st_month', '2nd_month', '3rd_month', 'Rookie_Month']]
fyp_date['Applied_Temp'] = fyp_date['POLICY ACKNOWLED'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
##BƯỚC NÀY: PHÂN RA CÁC FYP:
fyp_date['FYP_month'] = np.where(fyp_date['Applied_Temp'] <= fyp_date['1st_month'], "3",
                    np.where(fyp_date['Applied_Temp'] == fyp_date['2nd_month'], "2",
                    np.where(fyp_date['Applied_Temp'] == fyp_date['3rd_month'], "1", "")))
fyp_date = fyp_date.groupby(['Servicing Agent', 'FYP_month'])['FYP_Total'].sum().reset_index()
fyp_pivot = fyp_date.pivot(index='Servicing Agent', columns='FYP_month', values='FYP_Total').reset_index()
fyp_pivot = fyp_pivot.rename(columns={'1': 'FYP_1st', '2': 'FYP_2nd', '3': 'FYP_3rd'})
fyp_pivot

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\2083948580.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fyp_date['Applied_Temp'] = fyp_date['POLICY ACKNOWLED'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\2083948580.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fyp_date['FYP_month'] = np.where(fyp_date['Applied_Temp'] <= fyp_date['1st_month'], "3",

FYP_month Servicing Agent     FYP_1st      FYP_2nd     FYP_3rd
0                60005807  41990000.0   64533000.0         NaN
1                60007436         NaN   50030000.0         NaN
2                60007949  37320000.0  117020000.0         NaN
3                60009490         NaN   66084000.0  49251000.0
4                60010010         NaN  153152000.0         NaN
...                   ...         ...          ...         ...
1032             60077049  31332000.0          NaN         NaN
1033             60077055   8320000.0          NaN         NaN
1034             60077057  87763000.0          NaN         NaN
1035             60077084  79719000.0          NaN         NaN
1036             60077099  10058000.0          NaN         NaN

[1037 rows x 4 columns]

<h3> 4. Tính CaseCount

In [107]:
cc_agent = premium_table
cc_agent = cc_agent[['Policy No', 'PREM TRAN NAME', 'Applied Premium Date', 'POLICY ACKNOWLED', 'Issuing Agent', 'Freelook', 'Policy Status']].drop_duplicates()
cc_agent['PREM TRAN NAME'] = cc_agent['PREM TRAN NAME'].str.strip()
cc_agent = cc_agent[(cc_agent['PREM TRAN NAME'] == 'Contract Issue') & (cc_agent['Freelook'] > 21) &
            ~cc_agent['Policy Status'].isin(['CF', 'DC', 'FL',  'NT', 'WD', 'PO'])]
cc_agent

,Policy No,PREM TRAN NAME,Applied Premium Date,POLICY ACKNOWLED,Issuing Agent,Freelook,Policy Status
11,80002938,Contract Issue,2016-04-29,2016-05-07,60002527,2520.0,IF
25,80002939,Contract Issue,2016-04-29,2016-05-07,60003239,2520.0,LA
28,80002940,Contract Issue,2016-04-29,2016-05-04,60000879,2523.0,SU
115,80000584,Contract Issue,2015-08-27,2015-08-29,60000163,2772.0,IF
122,80001483,Contract Issue,2015-12-30,2016-01-07,60000682,2641.0,LA
...,...,...,...,...,...,...,...
1351364,80004872,Contract Issue,2016-08-23,2016-08-28,60004021,2407.0,IF
1351386,80004873,Contract Issue,2016-08-23,2016-08-25,60001823,2410.0,LA
1351387,80004874,Contract Issue,2016-08-23,2016-08-25,60004952,2410.0,LA
1351388,80004875,Contract Issue,2016-08-23,2016-08-25,60005250,2410.0,LA
1351431,80004825,Contract Issue,2016-08-18,2016-08-23,60005210,2412.0,IF

<h5> 4.1 Lọc ra các ngày trong kỳ tính toán:

In [115]:
cc_cal = pd.merge(cc_agent, agent_target, left_on = 'Issuing Agent', right_on ='Agent_Number', how = 'left')
cc_cal = cc_cal[['Policy No', 'PREM TRAN NAME', 'Applied Premium Date',
       'POLICY ACKNOWLED', 'Issuing Agent', 'Date_Appointed' ,'Freelook', 'Policy Status', 'Date_On_Set', 'Date_1st_Temp', '1st_month', '2nd_month', '3rd_month']]
cc_cal['Applied_Temp'] = cc_cal['POLICY ACKNOWLED'].dt.floor('d') + pd.offsets.MonthEnd(0) - pd.offsets.MonthBegin(1)
cc_cal = cc_cal[(cc_cal['POLICY ACKNOWLED'] >= cc_cal['Date_Appointed']) & (cc_cal['POLICY ACKNOWLED'] <= cc_cal['Date_On_Set'])]
cc_cal['CC_Month'] = np.where(cc_cal['Applied_Temp']<=cc_cal['1st_month'], "3",
                    np.where(cc_cal['Applied_Temp'] == cc_cal['2nd_month'], "2",
                    np.where(cc_cal['Applied_Temp'] == cc_cal['3rd_month'], "1", "")))
cc_cal = cc_cal[['Issuing Agent', 'Policy No', 'POLICY ACKNOWLED', 'CC_Month']].drop_duplicates()
cc_cal = cc_cal.groupby(['Issuing Agent', 'CC_Month'])['Policy No'].count().reset_index()
cc_cal = cc_cal.pivot(index='Issuing Agent', columns='CC_Month', values ='Policy No').reset_index()
cc_cal = cc_cal.rename(columns={'1':'CC_1st', '2': 'CC_2nd', '3':'CC_3rd'})
cc_cal

CC_Month Issuing Agent  CC_1st  CC_2nd  CC_3rd
0             60005807     1.0     3.0     NaN
1             60007436     NaN     2.0     NaN
2             60007949     1.0     3.0     NaN
3             60009490     NaN     2.0     2.0
4             60010010     NaN     4.0     NaN
...                ...     ...     ...     ...
1032          60077049     2.0     NaN     NaN
1033          60077055     1.0     NaN     NaN
1034          60077057     3.0     NaN     NaN
1035          60077084     3.0     NaN     NaN
1036          60077099     1.0     NaN     NaN

[1037 rows x 4 columns]

<h3> 5. Ghép lại thông tin

In [128]:
agent_rookie_bonus = pd.merge(pd.merge(agent_target, fyp_pivot, left_on = 'Agent_Number', right_on ='Servicing Agent', how = 'left'), 
        cc_cal, left_on ='Agent_Number', right_on = 'Issuing Agent', how='left')
rookie_bonus = agent_rookie_bonus[['Area_Name', 'Sales_Unit_Code', 'Sales_Unit', 'Agent_Number',
       'Agent_Name', 'Grade', 'Agent_Status', 'Date_Appointed', 'CUTOFF',
       'Date_On_Set', 'Date_1st_Temp', '1st_month', '2nd_month', '3rd_month',
       'Rookie_Month', 'FYP Target', 'CC Target', 'FYP_1st', 'FYP_2nd', 'FYP_3rd', 'CC_1st', 'CC_2nd', 'CC_3rd']]
for i in ['FYP_1st', 'FYP_2nd', 'FYP_3rd', 'CC_1st', 'CC_2nd', 'CC_3rd']:
    rookie_bonus[i] = rookie_bonus[i].fillna(0)
rookie_bonus['FYP_3month_CatchUp'] = np.where(rookie_bonus['Rookie_Month'] == '3',
    rookie_bonus['FYP_1st'] + rookie_bonus['FYP_2nd'] + rookie_bonus['FYP_3rd'], 0)
rookie_bonus['FYP_2month_CatchUp'] = np.where(rookie_bonus['Rookie_Month'] == '2',
rookie_bonus['FYP_1st'] + rookie_bonus['FYP_2nd'],0)
rookie_bonus

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\2834443674.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rookie_bonus[i] = rookie_bonus[i].fillna(0)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_15104\2834443674.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rookie_bonus['FYP_3month_CatchUp'] = np.where(rookie_bonus['Rookie_Month'] == '3',

,Area_Name,Sales_Unit_Code,Sales_Unit,Agent_Number,Agent_Name,Grade,Agent_Status,Date_Appointed,CUTOFF,Date_On_Set,...,FYP Target,CC Target,FYP_1st,FYP_2nd,FYP_3rd,CC_1st,CC_2nd,CC_3rd,FYP_3month_CatchUp,FYP_2month_CatchUp
0,AHL,AD642,Nguyễn Thị Hồng,60074670,TRẦN THỊ HOÀI ANH,FC,Enforce,2022-12-26,20230331,2023-03-31,...,72000000,6,0.0,0.0,24609000.0,0.0,0.0,2.0,24609000.0,0.0
1,AHN,AD840,AG Bùi Thị Bích Ngọc,60075282,HOÀNG THỊ HOA,FC,Enforce,2022-12-23,20230331,2023-03-31,...,72000000,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AHN,AD840,AG Bùi Thị Bích Ngọc,60075362,ĐỖ HUY THẮNG,FM,Enforce,2022-12-24,20230331,2023-03-31,...,72000000,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ACM,AD457,Phạm Phương Liên,60075425,NGUYỄN VĂN HÓA,FC,Enforce,2022-12-28,20230331,2023-03-31,...,72000000,6,0.0,28682000.0,36111000.0,0.0,2.0,2.0,64793000.0,0.0
4,AHP,AD747,AG Lê Minh Tuấn,60074460,ĐỖ MẠNH THẮNG,FC,Enforce,2022-12-15,20230331,2023-03-31,...,72000000,6,0.0,0.0,13163000.0,0.0,0.0,1.0,13163000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,YTH,AD966,Hoàng Thị Luân,60074521,DUMMY LÔ THỊ QUÀNH,FM,Enforce,2022-12-13,20230331,2023-03-31,...,72000000,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3117,YTH,AD966,Hoàng Thị Luân,60074523,DUMMY VI THỊ NGA,FM,Enforce,2022-12-13,20230331,2023-03-31,...,72000000,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3118,YTH,AD966,Hoàng Thị Luân,60077034,ĐINH VIẾT LONG,FM,Enforce,2023-03-07,20230331,2023-03-31,...,24000000,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3119,YTH,A1057,Ngô Thị Liên,60077150,DUMMY NGUYỄN THỊ YẾN,DM,Enforce,2023-03-08,20230331,2023-03-31,...,24000000,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3120,ABL,AD329,Trần Hữu Nghị,60072139,TRẦN QUỐC THÁI,FC,Enforce,2022-12-31,20230331,2023-03-31,...,72000000,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [129]:
rookie_bonus.to_csv('checkrookie.csv')